== Marlowe 3.0 tutorials

This document gives an overview of a set of Marlowe tutorials.


=== link:./introducing-marlowe.adoc[Introducing Marlowe]

This tutorial gives an overview of the ideas behind Marlowe, as a
domain-specific language embedded in Haskell. It also introduces
commitments and timeouts, which are central to how Marlowe works in a
blockchain context.

=== link:./escrow-ex.adoc[A first example: the escrow contract]

This tutorial introduces a simple financial contract in pseudocode,
before explaining how it is modified to work in Marlowe, giving the
first example of a Marlowe contract.

=== link:./marlowe-model.adoc[The Marlowe Model]

In this tutorial we look at our general approach to modelling contracts in Marlowe, and the context in which Marlowe contracts are executed: the Cardano blockchain. In doing this we also introduce some of the standard terminology that we will use in describing Marlowe.

=== link:./marlowe-step-by-step.adoc[Marlowe step by step]

This tutorial explains the five ways of building contracts in Marlowe. Four of these – `Pay`, `Let`, `If` and `When` – build a complex contract from simpler contracts, and the fifth, `Refund`, is a simple contract. 

In explaining these contracts we will also explain Marlowe _values_, _observations_ and _actions_, which are used to supply external information and inputs to a running contract to control how it will evolve.

=== link:./marlowe-data.adoc[Marlowe and its components as Haskell data types]

This tutorial formally introduces Marlowe as a Haskell data type, as well as presenting 
the different types used by the model, and discussing a
number of assumptions about the infrastructure in which contracts will
be run.

=== link:./marlowe-semantics.adoc[Understanding the semantics] IGNORE THIS

This tutorial gives an introduction to the formal semantics of Marlowe
by presenting an overview of the key Haskell definitions that interpret
inputs and transactions, as well as fitting those into a schematic
overview of how the components of the semantics work together.

=== link:./embedded-marlowe.adoc[Embedded Marlowe] NOT YET UPDATED

This tutorial shows how to use some simple features of Haskell to write
Marlowe contracts that are more readable, maintainable and reusable, by
revisiting the escrow contract.

=== link:./using-marlowe.adoc[Using Marlowe]

This tutorial shows you how to use Marlowe from within Haskell, and in
particular shows how to exercise a contract using the semantics given earlier.

=== link:./playground-overview.adoc[The Marlowe Playground] NOT YET UPDATED

This tutorial introduces the Marlowe Playground, an online tool for
creating embedded Marlowe contracts and interactively stepping through
their execution.

=== link:./actus-marlowe.adoc[ACTUS and Marlowe] NOT YET UPDATED

This tutorial gives an introduction to the general idea of the ACTUS
taxonomy, plus examples implemented in Marlowe.

=== link:./marlowe-plutus.adoc[Implementing Marlowe in Plutus] NOT YET UPDATED

So far these tutorials have dealt with Marlowe as a “stand alone”
artefact; this tutorial describes how Marlowe is implemented on
blockchain, using the “mockchain” that provides a high-fidelity
simulation of the Cardano SL layer.

____
These tutorials address the current version of
Marlowe, 3.0, which is implemented in the _Marlowe Playground_, and
available https://prod.meadow.marlowe.iohkdev.io[here].

The version covered in the ISoLA paper, and supported in the original
version of Meadow, is tagged as *v1.3* and is
available https://github.com/input-output-hk/marlowe/tree/v1.3[here].
____