var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(b,c,d){b!=Array.prototype&&b!=Object.prototype&&(b[c]=d.value)};$jscomp.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global&&null!=global?global:b};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(b,c,d,e){if(c){d=$jscomp.global;b=b.split(".");for(e=0;e<b.length-1;e++){var f=b[e];f in d||(d[f]={});d=d[f]}b=b[b.length-1];e=d[b];c=c(e);c!=e&&null!=c&&$jscomp.defineProperty(d,b,{configurable:!0,writable:!0,value:c})}};
$jscomp.polyfill("String.fromCodePoint",function(b){return b?b:function(b){for(var c="",e=0;e<arguments.length;e++){var f=Number(arguments[e]);if(0>f||1114111<f||f!==Math.floor(f))throw new RangeError("invalid_code_point "+f);65535>=f?c+=String.fromCharCode(f):(f-=65536,c+=String.fromCharCode(f>>>10&1023|55296),c+=String.fromCharCode(f&1023|56320))}return c}},"es6","es3");
var h$ghcjsbn_zero_i=h$c1(h$integerzmgmpZCGHCziIntegerziTypeziSzh_con_e,0),h$ghcjsbn_one_i=h$c1(h$integerzmgmpZCGHCziIntegerziTypeziSzh_con_e,1),h$ghcjsbn_negOne_i=h$c1(h$integerzmgmpZCGHCziIntegerziTypeziSzh_con_e,-1),h$ghcjsbn_null_b=[-1],h$ghcjsbn_zero_b=[0],h$ghcjsbn_one_b=[1,1],h$ghcjsbn_two31_b=[2,0,8],h$ghcjsbn_czero_b=[2,268435455,15],h$ghcjsbn_two31_i=h$c1(h$integerzmgmpZCGHCziIntegerziTypeziJpzh_con_e,h$ghcjsbn_two31_b),h$ghcjsbn_negTwo31_i=h$c1(h$integerzmgmpZCGHCziIntegerziTypeziSzh_con_e,
-2147483648);
function h$ghcjsbn_assertValid_i(b,c){if(1!==h$ghcjsbn_zero_b.length||0!==h$ghcjsbn_zero_b[0])throw Error("zero_b mutated");if(2!==h$ghcjsbn_one_b.length||1!==h$ghcjsbn_one_b[0]||1!==h$ghcjsbn_one_b[1])throw Error("one_b mutated");if(b.f===h$integerzmgmpZCGHCziIntegerziTypeziSzh_con_e){b=b.d1;if("number"!==typeof b)throw Error("invalid small integer: not a number");if((b|0)!==b)throw Error("invalid small integer: not a small int");}else{if(b.f===h$integerzmgmpZCGHCziIntegerziTypeziJpzh_con_e)c=!1;
else if(b.f===h$integerzmgmpZCGHCziIntegerziTypeziJnzh_con_e)c=!0;else throw Error("invalid integer: unexpected constructor");b=b.d1;h$ghcjsbn_assertValid_b(b,"assertValid_i");if(2>b[0])throw Error("invalid big integer: array too short");if(2===b[0]&&(0===b[2]>>3||c&&32===b[2]&&0===b[1]))throw Error("invalid big integer: in smallint range");}}
function h$ghcjsbn_assertValid_b(b,c){if(!Array.isArray(b))throw Error("invalid big integer: not an array");if("number"!==typeof b[0]||b[0]>b.length-1)throw Error("invalid big integer: incorrect number of limbs");if(0<b[0]&&0===b[b[0]])throw Error("invalid big integer: leading zero");for(c=1;c<=b[0];c++){var d=b[c];if("number"!==typeof d)throw Error("invalid big integer: limb is not a number");if((d&268435455)!==d)throw Error("invalid big integer: limb out of range");}}
function h$ghcjsbn_assertValid_s(b,c){if("number"!==typeof b)throw Error("invalid int: not a number");if((b|0)!==b)throw Error("invalid int: not in smallint range");}function h$ghcjsbn_assertValid_w(b,c){if("number"!==typeof b)throw Error("invalid word: not a number");if((b|0)!==b)throw Error("invalid word: not in smallint range");}function h$ghcjsbn_assertValid_d(b,c){if("number"!==typeof b)throw Error("invalid double: not a number");}
var h$ghcjsbn_smallPrimes=[2,3,5,7,11,13,17,19,23,29,31,37,41,43,47,53,59,61,67,71,73,79,83,89,97,101,103,107,109,113,127,131,137,139,149,151,157,163,167,173,179,181,191,193,197,199,211,223,227,229,233,239,241,251,257,263,269,271,277,281,283,293,307,311,313,317,331,337,347,349,353,359,367,373,379,383,389,397,401,409,419,421,431,433,439,443,449,457,461,463,467,479,487,491,499,503,509,521,523,541,547,557,563,569,571,577,587,593,599,601,607,613,617,619,631,641,643,647,653,659,661,673,677,683,691,701,
709,719,727,733,739,743,751,757,761,769,773,787,797,809,811,821,823,827,829,839,853,857,859,863,877,881,883,887,907,911,919,929,937,941,947,953,967,971,977,983,991,997],h$ghcjsbn_smallPrimesM=null;function h$ghcjsbn_getSmallPrimesM(){var b;if(null===h$ghcjsbn_smallPrimesM){var c=[];for(b=0;1008>b;b++)c[b]=!1;for(b=h$ghcjsbn_smallPrimes.length-1;0<=b;b--)c[h$ghcjsbn_smallPrimes[b]]=!0;h$ghcjsbn_smallPrimesM=c}return h$ghcjsbn_smallPrimesM}
function h$ghcjsbn_isPrime_s(b,c){if(2>b||2<b&&1===(b&1))return!1;if(1008>=b)return h$ghcjsbn_getSmallPrimesM()[b];throw Error("isPrime_s");}function h$ghcjsbn_isPrime_b(b,c){h$ghcjsbn_assertValid_b(b,"isPrime");throw Error("isPrime_b");}function h$ghcjsbn_cmp_bb(b,c){h$ghcjsbn_assertValid_b(b,"cmp_bb b1");h$ghcjsbn_assertValid_b(c,"cmp_bb b2");var d=b[0],e=c[0];if(d===e){for(;0<=--d;){e=b[d+1];var f=c[d+1];if(e!==f)return e<f?0:2}return 1}return d>e?2:0}
var h$ghcjsbn_tmp_2a=[0,0,0],h$ghcjsbn_tmp_2b=[0,0,0],h$ghcjsbn_tmp_a=[0,0,0,0,0,0,0,0],h$ghcjsbn_tmp_b=[0,0,0,0,0,0,0,0];function h$ghcjsbn_sub_bw(b,c){var d=h$ghcjsbn_tmp_2a;h$ghcjsbn_toBigNat_w(d,c);return h$ghcjsbn_sub_bb(b,d)}
function h$ghcjsbn_sub_bs(b,c){h$ghcjsbn_assertValid_b(b,"sub_bs");h$ghcjsbn_assertValid_s(c,"sub_bs");if(0>c)if(-2147483648===c)b=h$ghcjsbn_add_bb(b,h$ghcjsbn_two31_b);else{var d=h$ghcjsn_tmp_2a;h$ghcjsbn_toBigNat_s(d,-c);b=h$ghcjsbn_add_bb(b,d)}else d=h$ghcjsn_tmp_2a,h$ghcjsbn_toBigNat_s(d,c),b=h$ghcjsbn_sub_bb(b,d);h$ghcjsbn_assertValid_b(b,"sub_bs result");return b}
function h$ghcjsbn_add_bw(b,c){h$ghcjsbn_assertValid_b(b,"add_bw");h$ghcjsbn_assertValid_w(c,"add_bw");var d=h$ghcjsbn_tmp_2a;h$ghcjsbn_toBigNat_w(d,c);return h$ghcjsbn_add_bb(b,d)}
function h$ghcjsbn_add_bs(b,c){h$ghcjsbn_assertValid_b(b,"add_bs");h$ghcjsbn_assertValid_s(c,"add_bs");if(0>c)if(-2147483648===c)b=h$ghcjsbn_sub_bb(b,h$ghcjsbn_two31_r);else{var d=h$ghcjsbn_tmp_2a;h$ghcjsbn_toBigNat_s(d,-c);b=h$ghcjsbn_sub(b,d)}else d=h$ghcjsbn_tmp_2a,h$ghcjsbn_toBigNat_s(d,c),b=h$ghcjsbn_add_bb(b,d);h$ghcjsbn_assertValid_b(b,"add_bs result");return b}
function h$ghcjsbn_add_bb(b,c){h$ghcjsbn_assertValid_b(b,"add_bb b1");h$ghcjsbn_assertValid_b(c,"add_bb b2");var d=0;var e=b[0];var f=c[0],g=[0];if(e<=f){var h=e;var k=f;f=c}else h=f,k=e,f=b;for(e=1;e<=h;e++)d+=b[e]+c[e],g[e]=d&268435455,d>>=28;for(e=h+1;e<=k;e++)d+=f[e],g[e]=d&268435455,d>>=28;0!==d&&(g[++k]=d);g[0]=k;h$ghcjsbn_assertValid_b(g,"add_bb result");return g}
function h$ghcjsbn_addTo_bb(b,c){h$ghcjsbn_assertValid_b(b,"addTo_bb b1");h$ghcjsbn_assertValid_b(c,"addTo_bb b2");var d,e=0,f=b[0],g=c[0];if(g>f){for(d=f+1;d<=g;d++)b[d]=0;f=g}for(d=1;d<=g;d++)e+=b[d]+c[d],b[d]=e&268435455,e>>=28;for(d=g+1;0!==e&&d<=f;d++)e+=b[d],b[d]=e&268435455,e>>=28;0!==e?(b[f]=e,b[0]=f+1):b[0]=f;h$ghcjsbn_assertValid_b(b,"addTo_bb result")}
function h$ghcjsbn_sub_bb(b,c){h$ghcjsbn_assertValid_b(b,"sub_bb b1");h$ghcjsbn_assertValid_b(c,"sub_bb b2");if(0===h$ghcjsbn_cmp_bb(b,c))return[];var d,e=0,f=b[0],g=c[0],h=[0];for(d=1;d<=g;d++)e+=b[d]-c[d],h[d]=e&268435455,e>>=28;for(d=g+1;d<=f;d++)e+=b[d],h[d]=e&268435455,e>>=28;for(;0<f&&0===h[f];)f--;h[0]=f;h$ghcjsbn_assertValid_b(h,"sub_bb result");return h}
function h$ghcjsbn_subTo_bb(b,c){h$ghcjsbn_assertValid_b(b,"subTo_bb b1");h$ghcjsbn_assertValid_b(c,"subTo_bb b2");if(0===h$ghcjsbn_cmp_bb(b,c))throw Error("h$ghcjsbn_subTo_bb assertion failed: b1 >= b2");var d,e=0,f=b[0],g=c[0];for(d=1;d<=g;d++)e+=b[d]-c[d],b[d]=e&268435455,e>>=28;for(d=g+1;0!==e&&d<=f;d++)e+=b[d],b[d]=e&268435455,e>>=28;for(;0<f&&0===b[f];)f--;b[0]=f;h$ghcjsbn_assertValid_b(b,"subTo_bb result")}
function h$ghcjsbn_wrap_p(b){var c=b[0];return 0===c?h$c1(h$integerzmgmpZCGHCziIntegerziTypeziSzh_con_e,0):1===c?h$c1(h$integerzmgmpZCGHCziIntegerziTypeziSzh_con_e,b[1]):2===c&&0===b[2]>>3?h$c1(h$integerzmgmpZCGHCziIntegerziTypeziSzh_con_e,b[2]<<28|b[1]):h$c1(h$integerzmgmpZCGHCziIntegerziTypeziJpzh_con_e,b)}
function h$ghcjsbn_wrap_n(b){var c=b[0];return 0===c?h$c1(h$integerzmgmpZCGHCziIntegerziTypeziSzh_con_e,0):1===c?h$c1(h$integerzmgmpZCGHCziIntegerziTypeziSzh_con_e,-b[1]):2===c&&(0===b[2]>>31-GHCJSN_BITS||8===b[2]&&0===b[1])?h$c1(h$integerzmgmpZCGHCziIntegerziTypeziSzh_con_e,-b[2]-b[1]|0):h$c1(h$integerzmgmpZCGHCziIntegerziTypeziJnzh_con_e,b)}
function h$ghcjsbn_mulTo_bb(b,c){h$ghcjsbn_assertValid_b(b,"mulTo_bb b1");h$ghcjsbn_assertValid_b(c,"mulTo_bb b2");c=h$ghcjsbn_mul_bb(b,c);h$ghcjsbn_copy(b,c);h$ghcjsbn_assertValid_b(b,"mulTo_bb result")}
function h$ghcjsbn_mul_bb(b,c){h$ghcjsbn_assertValid_b(b,"mul_bb b1");h$ghcjsbn_assertValid_b(c,"mul_bb b2");var d=b[0],e=c[0],f=d+e,g,h=[0];for(g=1;g<=f;g++)h[g]=0;if(d>e)for(g=0;g<e;g++)h[g+d+1]=h$ghcjsbn_mul_limb(0,b,c[g+1],h,g,0,d);else for(g=0;g<d;g++)h[g+e+1]=h$ghcjsbn_mul_limb(0,c,b[g+1],h,g,0,e);for(g=d+e;0<g&&0===h[g];g--);h[0]=g;h$ghcjsbn_assertValid_b(h,"mul_bb result");return h}
function h$ghcjsbn_mul_bw(b,c){h$ghcjsbn_assertValid_b(b,"mul_bw");h$ghcjsbn_assertValid_w(c,"mul_bw");var d=h$ghcjsbn_tmp_2a;h$ghcjsbn_toBigNat_w(d,c);b=h$ghcjsbn_mul_bb(b,d);h$ghcjsbn_assertValid_b(b,"mul_bw result");return b}function h$ghcjsbn_mul_karatsuba_bb(b,c,d){throw Error("not yet updated");}function h$ghcjsbn_mul_limb(b,c,d,e,f,g,h){var k=d&16383;for(d>>=14;0<=--h;){var l=c[++b]&16383,m=c[b]>>14,p=d*l+m*k;l=k*l+((p&16383)<<14)+e[++f]+g;g=(l>>28)+(p>>14)+d*m;e[f]=l&268435455}return g}
function h$ghcjsbn_quotRem_bb(b,c,d,e){h$ghcjsbn_assertValid_b(d,"quotRem_bb b1");h$ghcjsbn_assertValid_b(e,"quotRem_bb b2");if(2!==h$ghcjsbn_cmp_bw(e,0))throw Error("h$ghcjsbn_quotRem_bb: operand not positive");null===b&&(b=h$ghcjsbn_tmp_a);null===c&&(c=h$ghcjsbn_tmp_b);var f=e[0],g=[];if(0===d[0])b[0]=0,c[0]=0;else if(0===h$ghcjsbn_cmp_bb(d,e))b[0]=0,h$ghcjsbn_copy(c,d);else{f=28-h$ghcjsbn_nbits_s(e[f]);h$ghcjsbn_assertValid_s(f,"quotRem_bb nsh");0!==f?(h$ghcjsbn_shlTo_b(g,e,f),h$ghcjsbn_shlTo_b(c,
d,f)):(h$ghcjsbn_copy(g,e),h$ghcjsbn_copy(c,d));h$ghcjsbn_assertValid_b(g,"quotRem_bb y_0");h$ghcjsbn_assertValid_b(c,"quotRem_bb r_0");d=g[0];e=g[d];var h=16777216*e+(1<d?g[d-1]>>4:0),k=4503599627370496/h;h=16777216/h;var l=c[0],m=l-d,p=b;h$ghcjsbn_shlTo_limbs_b(p,g,m);0!==h$ghcjsbn_cmp_bb(c,p)&&(c[c[0]+1]=1,c[0]+=1,h$ghcjsbn_subTo_bb(c,p));h$ghcjsbn_shlTo_limbs_b(p,h$ghcjsbn_one_b,d);for(g=h$ghcjsbn_sub_bb(p,g);g.length<=d;)g[g.length]=0;for(;0<=--m;){var n=c[--l+1]===e?268435455:Math.floor(c[l+
1]*k+(c[l]+16)*h),q=h$ghcjsbn_mul_limb(0,g,n,c,m,0,d);if((c[l+1]+=q)<n)for(h$ghcjsbn_shlTo_limbs_b(p,g,m),h$ghcjsbn_subTo_bb(c,p);c[l+1]<--n;)h$ghcjsbn_subTo_bb(c,p)}h$ghcjsbn_assertValid_b(c,"intermediate r");h$ghcjsbn_shrTo_limbs_b(b,c,d);for(c[0]=d;0===c[c[0]]&&0<c[0]&&c[0]--;);0!==f&&(g=[],h$ghcjsbn_copy(g,c),h$ghcjsbn_shrTo_b(c,g,f));h$ghcjsbn_assertValid_b(b,"quotRem_bb result q");h$ghcjsbn_assertValid_b(c,"quotRem_bb result r")}}
function h$ghcjsbn_quotRem_bw(b,c,d){h$ghcjsbn_assertValid_b(c,"quotRem_bw");h$ghcjsbn_assertValid_w(d,"quotRem_bw");var e=h$ghcjsbn_tmp_2a;h$ghcjsbn_toBigNat_w(e,d);d=[];h$ghcjsbn_quotRem_bb(b,d,c,e);return h$ghcjsbn_toWord_b(d)}function h$ghcjsbn_tmp_toJSBN(b){var c=new BigInteger,d=b[0],e;for(e=0;e<d;e++)c.data[e]=b[e+1];c.s=0;c.t=d;return c}function h$ghcjsbn_tmp_fromJSBN(b,c){var d=c.t,e;for(e=0;e<d;e++)b[e]=c.data[e];return d}
function h$ghcjsbn_rem_bb(b,c){h$ghcjsbn_assertValid_b(b,"rem_bb b1");h$ghcjsbn_assertValid_b(c,"rem_bb b2");var d=[];h$ghcjsbn_quotRem_bb([],d,b,c);h$ghcjsbn_assertValid_b(d,"rem_bb result");return d}function h$ghcjsbn_rem_bw(b,c){h$ghcjsbn_assertValid_b(b,"rem_bw");h$ghcjsbn_assertValid_w(c,"rem_bw");b=h$ghcjsbn_quotRem_bw([],b,c);h$ghcjsbn_assertValid_w(b,"rem_bw result");return b}
function h$ghcjsbn_quot_bb(b,c){h$ghcjsbn_assertValid_b(b,"quot_bb b1");h$ghcjsbn_assertValid_b(c,"quot_bb b2");var d=[];h$ghcjsbn_quotRem_bb(d,[],b,c);h$ghcjsbn_assertValid_b(d,"quot_bb result");return d}
function h$ghcjsbn_sqr_b(b){h$ghcjsbn_assertValid_b(b,"sqr_b");var c=b[0],d=2*c,e,f=[0];for(e=1;e<=d;e++)f[e]=0;for(e=0;e<c-1;e++){var g=h$ghcjsbn_mul_limb(e,b,b[e+1],f,2*e,0,1);268435456<=(f[e+c+1]+=h$ghcjsbn_mul_limb(e+1,b,2*b[e+1],f,2*e+1,g,c-e-1))&&(f[e+c+1]-=268435456,f[e+c+2]=1)}0<d&&(f[d]+=h$ghcjsbn_mul_limb(e,b,b[e+1],f,2*e,0,1));0===f[d]&&d--;f[0]=d;h$ghcjsbn_assertValid_b(f,"sqr_b result");return f}
function h$ghcjsbn_pow_bb(b,c){h$ghcjsbn_assertValid_b(b,"pow_bb b1");h$ghcjsbn_assertValid_b(c,"pow_bb b2");var d=b,e=[1,1],f=h$ghcjsbn_nbits_b(c);for(b=0;b<f;b++)h$ghcjsbn_testBit_b(c,b)&&h$ghcjsbn_mulTo_bb(e,d),d=h$ghcjsbn_sqr_b(d);return e}function h$ghcjsbn_pow_bw(b,c){h$ghcjsbn_assertValid_b(b,"pow_bw");h$ghcjsbn_assertValid_w(c,"pow_bw");for(var d=[1,1];c;)c&1&&h$ghcjsbn_mulTo_bb(d,b),(c>>>=1)&&(b=h$ghcjsbn_sqr_b(b));h$ghcjsbn_assertValid_b(d,"pow_bw result");return d}
function h$ghcjsbn_pow_ww(b,c){h$ghcjsbn_assertValid_s(b,"pow_ww w1");h$ghcjsbn_assertValid_s(c,"pow_ww w2");var d=h$ghcjsbn_tmp_2a;h$ghcjsbn_toBigNat_w(d,b);b=h$ghcjsbn_pow_bw(d,c);h$ghcjsbn_assertValid_b(b,"pow_ww result");return b}function h$ghcjsbn_modPow_bbb(b,c,d){throw Error("modPow_bbb");}function h$ghcjsbn_modPow_bss(b,c,d){throw Error("modPow_bss");}function h$ghcjsbn_modPow_sss(b,c,d){throw Error("modPow_sss");}
function h$ghcjsbn_gcd_bb(b,c){h$ghcjsbn_assertValid_b(b,"gcd_bb b1");h$ghcjsbn_assertValid_b(c,"gcd_bb b2");if(2===h$ghcjsbn_cmp_bb(b,c)){var d=b;b=c;c=d}for(;0<b[0];)d=h$ghcjsbn_rem_bb(c,b),c=b,b=d;h$ghcjsbn_assertValid_b(c,"gcd_bb result");return c}function h$ghcjsbn_gcd_bs(b,c){throw Error("h$ghcjsbn_gcd_bs not implemented");}
function h$ghcjsbn_gcd_ss(b,c){h$ghcjsbn_assertValid_s(b,"gcd_ss s1");h$ghcjsbn_assertValid_s(c,"gcd_ss s2");b=0>b?-b:b;c=0>c?-c:c;if(c<b){var d=b;b=c;c=d}for(;0!==b;)d=c%b,c=b,b=d;h$ghcjsbn_assertValid_s(c,"gcd_ss result");return c}function h$ghcjsbn_gcd_ww(b,c){h$ghcjsbn_assertValid_w(b,"gcd_ww w1");h$ghcjsbn_assertValid_w(c,"gcd_ww w2");b=0>b?b+4294967296:b;c=0>c?c+4294967296:c;if(c<b){var d=b;b=c;c=d}for(;0!==b;)d=c%b,c=b,b=d;c|=0;h$ghcjsbn_assertValid_w(c,"gcd_ww result");return c}
function h$ghcjsbn_gcd_bw(b,c){h$ghcjsbn_assertValid_b(b,"gcd_bw");h$ghcjsbn_assertValid_w(c,"gcd_bw");var d=h$ghcjsbn_quotRem_bw([],b,c);h$ghcjsbn_assertValid_w(d,"gcd_bw r");return 0===d?0===b[0]?0:c:h$ghcjsbn_gcd_ww(d,c)}
function h$ghcjsbn_shr_b(b,c){h$ghcjsbn_assertValid_b(b,"shr_b");h$ghcjsbn_assertValid_s(c,"shr_b");if(0>c)throw Error("h$ghcjsbn_shr_b: negative operand");var d=b[0],e=c/28|0,f=[0];d-=e;if(0>=d)f[0]=0;else{var g=c%28,h=28-g,k=(1<<g)-1,l=b[e+1]>>g;for(c=1;c<d;c++){var m=b[c+e+1];f[c]=(m&k)<<h|l;l=m>>g}0!==l?(f[d]=l,f[0]=d):f[0]=d-1}h$ghcjsbn_assertValid_b(f,"shr_b result");return f}
function h$ghcjsbn_shrTo_b(b,c,d){h$ghcjsbn_assertValid_b(c,"shrTo_b");h$ghcjsbn_assertValid_s(d,"shrTo_b");if(0>d)throw Error("h$ghcjsbn_shrTo_b: negative operand");var e=c[0],f=d/28|0;b[0]=0;e-=f;if(0>=e)b[0]=0;else{var g=d%28,h=28-g,k=(1<<g)-1,l=c[f+1]>>g;for(d=1;d<e;d++){var m=c[d+f+1];b[d]=(m&k)<<h|l;l=m>>g}0!==l?(b[e]=l,b[0]=e):b[0]=e-1}h$ghcjsbn_assertValid_b(b,"shrTo_b result")}function h$ghcjsbn_shr_neg_b(b,c){throw Error("shr_neg_b not implemented");}
function h$ghcjsbn_shl_b(b,c){h$ghcjsbn_assertValid_b(b,"shl_b");h$ghcjsbn_assertValid_s(c,"shl_b");if(0>c)throw Error("h$ghcjsbn_shl_b: negative operand");var d=c/28|0;c%=28;var e=28-c,f=b[0];if(0===f)return h$ghcjsbn_zero_b;var g=0,h,k=[0];for(h=1;h<=d;h++)k[h]=0;for(h=1;h<=f;h++){var l=b[h];k[h+d]=l<<c&268435455|g;g=l>>e}0!==g?(k[f+d+1]=g,k[0]=f+d+1):k[0]=f+d;h$ghcjsbn_assertValid_b(k,"shl_b result");return k}
function h$ghcjsbn_shlTo_b(b,c,d){h$ghcjsbn_assertValid_b(c,"shlTo_b");h$ghcjsbn_assertValid_s(d,"shlTo_b");if(0>d)throw Error("h$ghcjsbn_shlTo_b: negative operand");var e=d/28|0;d%=28;var f=28-d,g=c[0],h=0,k;b[0]=0;for(k=1;k<=e;k++)b[k]=0;for(k=1;k<=g;k++){var l=c[k];b[k+e]=l<<d&268435455|h;h=l>>f}0!==h?(b[g+e+1]=h,b[0]=g+e+1):b[0]=g+e;h$ghcjsbn_assertValid_b(b,"shlTo_b result")}
function h$ghcjsbn_shrTo_limbs_b(b,c,d){h$ghcjsbn_assertValid_b(c,"shrTo_limbs_b");h$ghcjsbn_assertValid_s(d,"shrTo_limbs_b");if(0>d)throw Error("h$ghcjsbn_shrTo_limbs_b: negative operand");var e=c[0]-d,f;if(1>e)b[0]=0;else for(b[0]=e,f=1;f<=e;f++)b[f]=c[f+d];h$ghcjsbn_assertValid_b(b,"shrTo_limbs_b result")}
function h$ghcjsbn_shlTo_limbs_b(b,c,d){h$ghcjsbn_assertValid_b(c,"shlTo_limbs_b");h$ghcjsbn_assertValid_s(d,"shlTo_limbs_b");if(0>d)throw Error("h$ghcjsbn_shlTo_limbs_b: negative operand");var e=c[0],f=e+d;if(0===e)b[0]=0;else{b[0]=f;for(e=1;e<=d;e++)b[e]=0;for(e=d+1;e<=f;e++)b[e]=c[e-d]}h$ghcjsbn_assertValid_b(b,"shlTo_limbs_b result")}
function h$ghcjsbn_nbits_b(b){h$ghcjsbn_assertValid_b(b,"nbits_b");var c=b[0];if(0===c)return 0;b=28*(c-1)+h$ghcjsbn_nbits_s(b[c]);h$ghcjsbn_assertValid_s(b,"nbits_b result");return b}function h$ghcjsbn_nbits_s(b){h$ghcjsbn_assertValid_s(b,"nbits_s");var c=1,d;0!=(d=b>>>16)&&(b=d,c+=16);0!=(d=b>>8)&&(b=d,c+=8);0!=(d=b>>4)&&(b=d,c+=4);0!=(d=b>>2)&&(b=d,c+=2);0!=b>>1&&(c+=1);h$ghcjsbn_assertValid_s(c,"nbits_s result");return c}
function h$ghcjsbn_showBase(b,c){h$ghcjsbn_assertValid_b(b,"showBase");h$ghcjsbn_assertValid_s(c,"showBase");return 1===h$ghcjsbn_cmp_bb(b,h$ghcjsbn_zero_b)?"0":h$ghcjsbn_showBase_rec(b,c,Math.log(c),0)}
function h$ghcjsbn_showBase_rec(b,c,d,e){var f=h$ghcjsbn_nbits_b(b);if(0===h$ghcjsbn_cmp_bb(b,h$ghcjsbn_two31_b))b=h$ghcjsbn_toInt_b(b),f=0===b?"":b.toString(c);else{var g=Math.round(Math.floor(.6931471805599453*f/d)/2),h=[];f=[];var k=h$ghcjsbn_pow_ww(c,g);h$ghcjsbn_quotRem_bb(h,f,b,k);f=h$ghcjsbn_showBase_rec(h,c,d,0)+h$ghcjsbn_showBase_rec(f,c,d,g)}c=f.length;if(c<e){for(;c<=e-8;)f="00000000"+f,c+=8;switch(e-c){case 1:f="0"+f;break;case 2:f="00"+f;break;case 3:f="000"+f;break;case 4:f="0000"+f;
break;case 5:f="00000"+f;break;case 6:f="000000"+f;break;case 7:f="0000000"+f}}return f}function h$ghcjsbn_show(b){return h$ghcjsbn_showBase(b,10)}function h$ghcjsbn_showHex(b){return h$ghcjsbn_showBase(b,16)}function h$ghcjsbn_readBigNat(b){return(b=/^\s*(\d+)\s*/.exec(b))?h$ghcjsbn_readBigNatDigits(b[1]):[0]}
function h$ghcjsbn_readBigNatDigits(b){if(9<b.length){var c=b.length/2|0,d=b.substring(0,c);c=b.substring(c);b=h$ghcjsbn_pow_ww(10,c.length);d=h$ghcjsbn_readBigNatDigits(d);c=h$ghcjsbn_readBigNatDigits(c);return h$ghcjsbn_add_bb(h$ghcjsbn_mul_bb(d,b),c)}return h$ghcjsbn_mkBigNat_w(parseInt(b))}
function h$ghcjsbn_readInteger(b){var c=/^\s*-?([0-9]+)\s*/.exec(b);if(!c)return null;c=c[1];b=-1!==b.indexOf("-");if(9>=c.length)return b?h$c1(h$integerzmgmpZCGHCziIntegerziTypeziSzh_con_e,-parseInt(c,10)):h$c1(h$integerzmgmpZCGHCziIntegerziTypeziSzh_con_e,parseInt(c,10));c=h$ghcjsbn_readBigNat(c);return b?h$c1(h$integerzmgmpZCGHCziIntegerziTypeziJnzh_con_e,c):h$c1(h$integerzmgmpZCGHCziIntegerziTypeziJpzh_con_e,c)}
function h$ghcjsbn_copy(b,c){h$ghcjsbn_assertValid_b(c,"copy");for(var d=c[0],e=0;e<=d;e++)b[e]=c[e];return d}function h$ghcjsbn_testBit_b(b,c){h$ghcjsbn_assertValid_b(b,"testBit_b");h$ghcjsbn_assertValid_s(c,"testBit_b");var d=c/28|0;return d>=b[0]?!1:0!==(b[d]&1<<c-28*d)}function h$ghcjsbn_popCount_b(b){h$ghcjsbn_assertValid_b(b,"popCount_b");for(var c=0,d=b[0];0<d;)c+=h$popCnt32(b[d--]);return c}
function h$ghcjsbn_xor_bb(b,c){h$ghcjsbn_assertValid_b(b,"xor_bb b1");h$ghcjsbn_assertValid_b(c,"xor_bb b2");var d=b[0];var e=c[0];var f=[0];if(d<=e){var g=d;var h=c}else g=e,e=d,h=b;for(d=1;d<=g;d++)f[d]=b[d]^c[d];for(d=g+1;d<=e;d++)f[d]=h[d];for(;0<e&&0===f[e];)e--;f[0]=e;h$ghcjsbn_assertValid_b(f,"xor_bb result");return f}
function h$ghcjsbn_or_bb(b,c){h$ghcjsbn_assertValid_b(b,"or_bb b1");h$ghcjsbn_assertValid_b(c,"or_bb b2");var d=b[0];var e=c[0];var f=[0];if(d<=e){var g=d;var h=c}else g=e,e=d,h=b;for(d=1;d<=g;d++)f[d]=b[d]|c[d];for(d=g+1;d<=e;d++)f[d]=h[d];f[0]=e;h$ghcjsbn_assertValid_b(f,"or_bb result");return f}
function h$ghcjsbn_and_bb(b,c){h$ghcjsbn_assertValid_b(b,"and_bb b1");h$ghcjsbn_assertValid_b(c,"and_bb b2");var d=b[0];var e=c[0];var f=[0];e=d<=e?d:e;for(d=1;d<=e;d++)f[d]=b[d]&c[d];for(;0<e&&0===f[e];)e--;f[0]=e;h$ghcjsbn_assertValid_b(f,"and_bb result");return f}
function h$ghcjsbn_andn_bb(b,c){h$ghcjsbn_assertValid_b(b,"andn_bb b1");h$ghcjsbn_assertValid_b(c,"andn_bb b2");var d,e=b[0],f=c[0],g=[0];if(e<=f)for(d=0;d<=e;d++)g[d]=b[d]&~c[d];else{for(d=0;d<=f;d++)g[d]=b[d]&~c[d];for(d=f+1;d<=e;d++)g[d]=b[d]}for(;0<e&&0===g[e];)e--;g[0]=e;h$ghcjsbn_assertValid_b(g,"andn_bb result");return g}function h$ghcjsbn_toInt_b(b){h$ghcjsbn_assertValid_b(b,"toInt_b");var c=b[0];b=2<=c?b[2]<<28|b[1]:1===c?b[1]:0;h$ghcjsbn_assertValid_s(b,"toInt_b result");return b}
function h$ghcjsbn_toWord_b(b){h$ghcjsbn_assertValid_b(b,"toWord_b");var c=b[0];b=2<=c?b[2]<<28|b[1]:1===c?b[1]:0;h$ghcjsbn_assertValid_w(b,"toWord_b result");return b}var h$integer_bigNatToWord64=h$ghcjsbn_toWord64_b,h$integer_word64ToBigNat=h$ghcjsbn_mkBigNat_ww;
function h$ghcjsbn_toWord64_b(b){h$ghcjsbn_assertValid_b(b,"toWord64_b");var c=b[0];if(2>c){var d=0;var e=1===c?b[1]:0}else e=b[1]|b[2]<<28,d=2===c?b[2]>>>4:b[2]>>>4|b[3]<<24;h$ghcjsbn_assertValid_w(d,"toWord64_b result w2");h$ghcjsbn_assertValid_w(e,"toWord64_b result w1");h$ret1=e;return d}
function h$ghcjsbn_toBigNat_s(b,c){h$ghcjsbn_assertValid_s(c,"toBigNat_s");if(0>c)throw Error("h$ghcjsbn_toBigNat_s: negative operand");0===c?b[0]=0:268435455>=c?(b[0]=1,b[1]=c):(b[0]=2,b[1]=c&268435455,b[2]=c>>268435455);h$ghcjsbn_assertValid_b(b,"toBigNat_s result")}function h$ghcjsbn_toBigNat_w(b,c){h$ghcjsbn_assertValid_w(c,"toBigNat_w");0===c?b[0]=0:0<c&&268435455>=c?(b[0]=1,b[1]=c):(b[0]=2,b[1]=c&268435455,b[2]=c>>>28);h$ghcjsbn_assertValid_b(b,"toBigNat_w result")}
function h$ghcjsbn_mkBigNat_w(b){h$ghcjsbn_assertValid_w(b,"mkBigNat_w");b=0===b?h$ghcjsbn_zero_b:1===b?h$ghcjsbn_one_b:0<b&&268435455>=b?[1,b]:[2,b&268435455,b>>>28];h$ghcjsbn_assertValid_b(b,"mkBigNat_w result");return b}
function h$ghcjsbn_mkBigNat_ww(b,c){h$ghcjsbn_assertValid_w(b,"mkBigNat_ww hw");h$ghcjsbn_assertValid_w(c,"mkBigNat_ww lw");if(0===b)var d=h$ghcjsbn_mkBigNat_w(c);else d=c&268435455,c=c>>>28|b<<4&268435455,b>>>=24,d=0===b?[2,d,c]:[3,d,c,b];h$ghcjsbn_assertValid_b(d,"mkBigNat_ww result");return d}var h$ghcjsbn_toBigNat_ww=h$ghcjsbn_mkBigNat_ww,h$integer_mkInteger=h$ghcjsbn_mkInteger;
function h$ghcjsbn_mkInteger(b,c){for(var d=[0],e=0,f;c.f===h$ghczmprimZCGHCziTypesziZC_con_e;)f=h$ghcjsbn_shl_b(h$ghcjsbn_mkBigNat_w("number"===typeof c.d1?c.d1:c.d1.d1),e),h$ghcjsbn_addTo_bb(d,f),e+=31,c=c.d2;if(b)return 0===h$ghcjsbn_cmp_bb(d,h$ghcjsbn_two31_b)?h$c1(h$integerzmgmpZCGHCziIntegerziTypeziSzh_con_e,h$ghcjsbn_toInt_b(d)):h$c1(h$integerzmgmpZCGHCziIntegerziTypeziJpzh_con_e,d);b=h$ghcjsbn_cmp_bb(d,h$ghcjsbn_two31_b);return 2===b?h$c1(h$integerzmgmpZCGHCziIntegerziTypeziJnzh_con_e,d):
1===b?h$ghcjsbn_negTwo31_i:h$c1(h$integerzmgmpZCGHCziIntegerziTypeziSzh_con_e,-h$ghcjsbn_toInt_b(d))}function h$ghcjsbn_indexBigNat(b,c){h$ghcjsbn_assertValid_b(b,"indexBigNat");h$ghcjsbn_assertValid_s(c,"indexBigNat");return c>=b[0]?0:b[c+1]}
function h$ghcjsbn_cmp_bw(b,c){h$ghcjsbn_assertValid_b(b,"cmp_bw");h$ghcjsbn_assertValid_w(c,"cmp_bw");var d=c&268435455;c>>>=28;var e=b[0];if(0===c)return 0===e?0<d?0:1:1===e?(b=b[1],b>d?2:b===d?1:0):2;if(2>e)return 0;if(2<e)return 2;e=b[1];b=b[2];return b>c?2:b<c?0:e>d?2:e<d?0:1}
function h$ghcjsbn_gt_bw(b,c){h$ghcjsbn_assertValid_b(b,"gt_bw");h$ghcjsbn_assertValid_w(c,"gt_bw");var d=b[0];if(2<d)return!0;if(0===d)return!1;if(1===d)return 0<=c&&b[1]>c;d=c>>>28;var e=b[2];return e>d||d===e&&b[1]>(c&268435455)}function h$ghcjsbn_eq_bb(b,c){h$ghcjsbn_assertValid_b(b,"eq_bb");h$ghcjsbn_assertValid_b(c,"eq_bb");var d=b[0];if(d!==c[0])return!1;for(;1<=d;d--)if(b[d]!==c[d])return!1;return!0}
function h$ghcjsbn_neq_bb(b,c){h$ghcjsbn_assertValid_b(b,"neq_bb");h$ghcjsbn_assertValid_b(c,"neq_bb");var d=b[0];if(d!==c[0])return!0;for(;1<=d;d--)if(b[d]!==c[d])return!0;return!1}function h$ghcjsbn_eq_bw(b,c){h$ghcjsbn_assertValid_b(b,"eq_bw");h$ghcjsbn_assertValid_w(c,"eq_bw");var d=c&268435455,e=c>>>28,f=b[0];return 0===e?0===d?0===f:1===f&&b[1]===c:2===f&&b[1]===d&&b[2]===e}function h$ghcjsbn_isZero_b(b){h$ghcjsbn_assertValid_b(b,"isZero_b");return 0===b[0]}
function h$ghcjsbn_isNull_b(b){return-1===b[0]}function h$ghcjsbn_bitBigNat(b){if(0>b)throw Error("bitBigNat: argument must be positive");if(0===b)d=h$ghcjsbn_one_b;else if(28>b)d=[1,1<<b];else{for(var c=b/28|0,d=[c+1],e=1;e<=c;e++)d[e]=0;d[c+1]=1<<b-28*c}h$ghcjsbn_assertValid_b(d,"bitBigNat result");return d}function h$ghcjsbn_integerLog2(b){h$ghcjsbn_assertValid_i(b,"integerLog2");return b.f===h$integerzmgmpZCGHCziIntegerziTypeziSzh_con_e?h$ghcjsbn_nbits_s(b.d1):h$ghcjsbn_nbits_b(b.d1)}
function h$ghcjsbn_integerLog2IsPowerOf2(b){h$ghcjsbn_assertValid_i(b,"integerLog2IsPowerOf2");if(b.f===h$integerzmgmpZCGHCziIntegerziTypeziSzh_con_e){var c=b.d1;h$ghcjsbn_assertValid_s(c,"integerLog2IsPowerOf2 sd");var d=h$ghcjsbn_nbits_s(c);return c===1<<d?-d:d}c=b.d1;h$ghcjsbn_assertValid_b(c,"integerLog2IsPowerOf2 bd");d=h$ghcjsbn_nbits_b(c);b=d/28|0;if(c[b+1]!==1<<d-28*b)return d;for(;1<=b;b--)if(0!==c[b])return d;return-d}
function h$ghcjsbn_isValid_b(b){if(!Array.isArray(b)||1>b.length)return 0;var c=b[0];if(b.length<c+1)return 0;for(var d=0;d<=c;d++){var e=b[d];if("number"!==typeof e||(e&268435455)!==e)return 0}return 1}function h$ghcjsbn_toInteger_b(b){h$ghcjsbn_assertValid_b(b,"toInteger_b");return 0===h$ghcjsbn_cmp_bb(b,h$ghcjsbn_two31_b)?h$c1(h$integerzmgmpZCGHCziIntegerziTypeziSzh_con_e,h$ghcjsbn_toInt_b(b)):h$c1(h$integerzmgmpZCGHCziIntegerziTypeziJpzh_con_e,b)}
function h$ghcjsbn_toNegInteger_b(b){h$ghcjsbn_assertValid_b(b,"toNegInteger_b");var c=h$ghcjsbn_cmp_bb(b,h$ghcjsbn_two31_b);return 0===c?h$c1(h$integerzmgmpZCGHCziIntegerziTypeziSzh_con_e,-h$ghcjsbn_toInt_b(b)):1===c?h$ghcjsbn_negTwo31_i:h$c1(h$integerzmgmpZCGHCziIntegerziTypeziJnzh_con_e,b)}function h$ghcjsbn_sizeof_b(b){return 1>b.length?0:Math.ceil(28*b[0]/32)}function h$ghcjsbn_index_b(b,c){throw Error("index_b");}function h$ghcjsbn_toDouble_b(b,c){throw Error("toDouble_b");}
function h$ghcjsbn_byteArrayToBigNat(b,c){throw Error("h$ghcjsbn_byteArrayToBigNat not yet implemented");}function h$ghcjsbn_importBigNatFromAddr(b,c,d,e){throw Error("h$ghcjsbn_importBigNatFromAddr not yet implemented");}function h$ghcjsbn_importBigNatFromByteArray(b,c,d,e){throw Error("h$ghcjsbn_importBigNatFromByteArray not yet implemented");}var h$integer_int64ToInteger=h$ghcjsbn_toInteger_s64;
function h$ghcjsbn_toInteger_s64(b,c){h$ghcjsbn_assertValid_s(b,"toInteger_s64 s_a");h$ghcjsbn_assertValid_s(c,"toInteger_s64 s_b");return 0===b?0<=c?h$c1(h$integerzmgmpZCGHCziIntegerziTypeziSzh_con_e,c):h$c1(h$integerzmgmpZCGHCziIntegerziTypeziJpzh_con_e,h$ghcjsbn_mkBigNat_w(c)):-1===b?0>c?h$c1(h$integerzmgmpZCGHCziIntegerziTypeziSzh_con_e,c):0===c?h$c1(h$integerzmgmpZCGHCziIntegerziTypeziJnzh_con_e,h$ghcjsbn_mkBigNat_ww(1,0)):h$c1(h$integerzmgmpZCGHCziIntegerziTypeziJnzh_con_e,h$ghcjsbn_mkBigNat_w(~c+
1|0)):0<b?h$c1(h$integerzmgmpZCGHCziIntegerziTypeziJpzh_con_e,h$ghcjsbn_mkBigNat_ww(b,c)):0===c?h$c1(h$integerzmgmpZCGHCziIntegerziTypeziJnzh_con_e,h$ghcjsbn_mkBigNat_ww(~b+1|0,0)):h$c1(h$integerzmgmpZCGHCziIntegerziTypeziJnzh_con_e,h$ghcjsbn_mkBigNat_ww(~b|0,~c+1|0))}
function h$decodeDoubleInt64(b){h$ghcjsbn_assertValid_d(b,"DoubleDecode_Int64");if(isNaN(b))return h$ret1=-1572864,h$ret2=0,972;h$convertDouble[0]=b;var c=h$convertInt[1],d=(c&2146435072)>>>20,e=h$convertInt[0];if(0===d)if(0===(c&2147483647)&&0===e)var f=d=0;else h$convertDouble[0]=9007199254740992*b,c=h$convertInt[1],d=c&1048575|1048576,e=h$convertInt[0],f=((c&2146435072)>>>20)-1128;else f=d-1075,d=c&1048575|1048576;0>b&&(0===e?d=~d+1|0:(d=~d,e=~e+1|0));h$ret1=d;h$ret2=e;return f}
function h$primop_DoubleDecode_Int64Op(b){h$ghcjsbn_assertValid_d(b,"DoubleDecode_Int64");if(isNaN(b))return h$ret1=-1572864,h$ret2=0,h$ret3=972,null;h$convertDouble[0]=b;var c=h$convertInt[1],d=(c&2146435072)>>>20,e=h$convertInt[0];if(0===d)if(0===(c&2147483647)&&0===e)var f=d=0;else h$convertDouble[0]=9007199254740992*b,c=h$convertInt[1],d=c&1048575|1048576,e=h$convertInt[0],f=((c&2146435072)>>>20)-1128;else f=d-1075,d=c&1048575|1048576;0>b&&(0===e?d=~d+1|0:(d=~d,e=~e+1|0));h$ret1=d;h$ret2=e;h$ret3=
f;return null}function h$ghcjsbn_encodeDouble_b(b,c,d){h$ghcjsbn_assertValid_b(c,"encodeDouble_b");h$ghcjsbn_assertValid_s(d,"encodeDouble_b");if(972<=d)return b?Infinity:-Infinity;var e=c[0],f=c[e];for(--e;1<=e;e--)f=268435456*f+1*c[e];f=600<d?f*Math.pow(2,d-600)*Math.pow(2,600):-600>d?f*Math.pow(2,d+600)*Math.pow(2,-600):f*Math.pow(2,d);h$ghcjsbn_assertValid_d(f,"encodeDouble_b result");return b?f:-f}function h$ghcjsbn_toDouble_b(b,c){return h$ghcjsbn_encodeDouble_b(b,c,0)}
var h$ghcjsbn_encodeDouble_i=h$ghcjsbn_encodeDouble_s;function h$ghcjsbn_encodeDouble_s(b,c){h$ghcjsbn_assertValid_s(b,"encodeDouble_s m");h$ghcjsbn_assertValid_s(c,"encodeDouble_s e");b*=Math.pow(2,c);h$ghcjsbn_assertValid_d(b,"encodeDouble_s result");return b}function h$createWebSocket(b,c){return new WebSocket(b,c)}
function h$openWebSocket(b,c,d,e){if(0!==b.readyState)throw Error("h$openWebSocket: unexpected readyState, socket must be CONNECTING");b.lastError=null;b.onopen=function(){c&&(b.onmessage=c);if(d||c)b.onclose=function(c){b.onmessage&&(h$release(b.onmessage),b.onmessage=null);d&&(h$release(d),d(c))};b.onerror=function(c){b.lastError=c;b.onmessage&&(h$release(b.onmessage),b.onmessage=null);b.close()};e(null)};b.onerror=function(f){d&&h$release(d);c&&h$release(c);b.onmessage=null;b.close();e(f)}}
function h$closeWebSocket(b,c,d){d.onerror=null;d.onmessage&&(h$release(d.onmessage),d.onmessage=null);d.close(b,c)}function h$fromArray(b){for(var c=h$ghczmprimZCGHCziTypesziZMZN,d=b.length-1;0<=d;d--)c=h$c2(h$ghczmprimZCGHCziTypesziZC_con_e,h$c1(h$ghcjszmprimZCGHCJSziPrimziJSVal_con_e,b[d]),c);return b}function h$fromArrayNoWrap(b){for(var c=h$ghczmprimZCGHCziTypesziZMZN,d=b.length-1;0<=d;d--)c=h$c2(h$ghczmprimZCGHCziTypesziZC_con_e,b[d],c);return b}
function h$listToArray(b){for(var c=[],d=0;b.f===h$ghczmprimZCGHCziTypesziZC_con_e;)c[d++]=b.d1.d1,b=b.d2;return c}function h$listToArrayWrap(b){return h$c1(h$ghcjszmprimZCGHCJSziPrimziJSVal_con_e,h$listToArray(b))}function h$animationFrameCancel(b){b.handle&&window.cancelAnimationFrame(b.handle);b.callback&&(h$release(b.callback),b.callback=null)}function h$animationFrameRequest(b){b.handle=window.requestAnimationFrame(function(c){var d=b.callback;d&&(h$release(d),b.callback=null,d(c))})}
function h$exportValue(b,c,d,e,f){b={fp1a:b,fp1b:c,fp2a:d,fp2b:e,released:!1,root:f,_key:-1};h$retain(b);return b}function h$derefExport(b,c,d,e,f){return!f||"object"!==typeof f||f.released||b!==f.fp1a||c!==f.fp1b||d!==f.fp2a||e!==f.fp2b?null:f.root}function h$releaseExport(b){h$release(b);b.released=!0;b.root=null}
var h$jsstringEmpty=h$c1(h$ghcjszmprimZCGHCJSziPrimziJSVal_con_e,""),h$jsstringHead,h$jsstringTail,h$jsstringCons,h$jsstringSingleton,h$jsstringSnoc,h$jsstringUncons,h$jsstringIndex,h$jsstringUncheckedIndex,h$fromCodePoint;
h$fromCodePoint=String.prototype.fromCodePoint?String.fromCodePoint:function(){var b=String.fromCharCode,c=Math.floor;return function(d){var e=[],f=-1,g=arguments.length;if(!g)return"";for(var h="";++f<g;){var k=Number(arguments[f]);if(!isFinite(k)||0>k||1114111<k||c(k)!=k)throw RangeError("Invalid code point: "+k);if(65535>=k)e.push(k);else{k-=65536;var l=(k>>10)+55296;k=k%1024+56320;e.push(l,k)}if(f+1==g||16384<e.length)h+=b.apply(null,e),e.length=0}return h}}();
String.prototype.codePointAt?(h$jsstringSingleton=function(b){return String.fromCodePoint(b)},h$jsstringHead=function(b){b=b.codePointAt(0);return void 0===b?-1:b|0},h$jsstringTail=function(b){if(0===b.length)return null;var c=b.codePointAt(0);return void 0===c?null:b.substr(65536<=c?2:1)},h$jsstringCons=function(b,c){return String.fromCodePoint(b)+c},h$jsstringSnoc=function(b,c){return b+String.fromCodePoint(c)},h$jsstringUncons=function(b){if(0===b.length)return h$ret1=null,-1;var c=b.codePointAt(0);
if(void 0===c)return h$ret1=null,-1;h$ret1=b.substr(65536<=c?2:1);return c},h$jsstringIndex=function(b,c){b=c.codePointAt(b);return void 0===b?-1:b},h$jsstringUncheckedIndex=function(b,c){return c.codePointAt(b)}):(h$jsstringSingleton=function(b){return 65536<=b?String.fromCharCode((b-65536>>>10)+56320,(b&1023)+55296):String.fromCharCode(b)},h$jsstringHead=function(b){var c=b.length;if(0===c)return-1;var d=b.charCodeAt(0);return 56319===(d|1023)?1<c?(d-55296<<10)+b.charCodeAt(1)-9216:-1:d},h$jsstringTail=
function(b){var c=b.length;return 0===c?null:56319===(b.charCodeAt(0)|1023)?1<c?b.substr(2):null:b.substr(1)},h$jsstringCons=function(b,c){return(65536<=b?String.fromCharCode((b-65536>>>10)+56320,(b&1023)+55296):String.fromCharCode(b))+c},h$jsstringSnoc=function(b,c){return b+(65536<=c?String.fromCharCode((c-65536>>>10)+56320,(c&1023)+55296):String.fromCharCode(c))},h$jsstringUncons=function(b){var c=b.length;if(0===c)return h$ret1=null,-1;var d=b.charCodeAt(0);if(56319===(d|1023)){if(1<c)return h$ret1=
b.substr(2),(d-55296<<10)+b.charCodeAt(1)-9216;h$ret1=null;return-1}h$ret1=b.substr(1);return d},h$jsstringIndex=function(b,c){var d=c.charCodeAt(b);return d!=d?-1:56319===(d|1023)?(d-55296<<10)+c.charCodeAt(b+1)-9216:d},h$jsstringUncheckedIndex=function(b,c){var d=c.charCodeAt(b);return 56319===(d|1023)?(d-55296<<10)+c.charCodeAt(b+1)-9216:d});
function h$jsstringPack(b){for(var c="",d=0,e=[],f;b.f===h$ghczmprimZCGHCziTypesziZC_con_e;)f=b.d1,e[d++]="number"===typeof f?f:f.d1,6E4<=d&&(c+=h$fromCodePoint.apply(null,e),e=[],d=0),b=b.d2;0<d&&(c+=h$fromCodePoint.apply(null,e));return c}function h$jsstringPackReverse(b){for(var c=[],d=0,e;b.f===h$ghczmprimZCGHCziTypesziZC_con_e;)e=b.d1,c[d++]="number"===typeof e?e:e.d1,b=b.d2;return 0===d?"":h$jsstringConvertArray(c.reverse())}function h$jsstringPackArray(b){return h$jsstringConvertArray(b)}
function h$jsstringPackArrayReverse(b){return h$jsstringConvertArray(b.reverse())}function h$jsstringConvertArray(b){if(6E4>b.length)return h$fromCodePoint.apply(null,b);for(var c="",d=0;d<b.length;d+=6E4)c+=h$fromCodePoint.apply(null,b.slice(d,d+6E4));return c}function h$jsstringInit(b){var c=b.length;if(0===c)return null;var d=b.charCodeAt(c-1);return b.substr(0,c-(57343===(d|1023)?2:1))}
function h$jsstringLast(b){var c=b.length;if(0===c)return-1;var d=b.charCodeAt(c-1);return 57343===(d|1023)?1<c?(b.charCodeAt(c-2)-55296<<10)+d-9216:-1:d}function h$jsstringIndexR(b,c){if(0>b||b>c.length)return-1;var d=c.charCodeAt(b);return 57343===(d|1023)?(c.charCodeAt(b-1)-55296<<10)+d-9216:d}function h$jsstringNextIndex(b,c){return b+(56319===(c.charCodeAt(b)|1023)?2:1)}
function h$jsstringTake(b,c){if(0>=b)return"";var d=0,e=c.length;if(b>=e)return c;for(;b--;){var f=c.charCodeAt(d++);56319===(f|1023)&&d++;if(d>=e)return c}return c.substr(0,d)}function h$jsstringDrop(b,c){if(0>=b)return c;var d=0,e=c.length;if(b>=e)return"";for(;b--;){var f=c.charCodeAt(d++);56319===(f|1023)&&d++;if(d>=e)return c}return c.substr(d)}
function h$jsstringSplitAt(b,c){if(0>=b)return h$ret1=c,"";if(b>=c.length)return h$ret1="",c;for(var d=0,e=c.length,f;b--;)if(f=c.charCodeAt(d++),56319===(f|1023)&&d++,d>=e)return h$ret1="",c;h$ret1=c.substr(d);return c.substr(0,d)}function h$jsstringTakeEnd(b,c){if(0>=b)return"";var d=c.length,e=d-1;if(b>=d)return c;for(;b--&&0<e;)d=c.charCodeAt(e--),57343===(d|1023)&&e--;return 0>e?c:c.substr(e+1)}
function h$jsstringDropEnd(b,c){if(0>=b)return c;var d=c.length,e=d-1;if(b>=d)return"";for(;b--&&0<e;)d=c.charCodeAt(e--),57343===(d|1023)&&e--;return 0>e?"":c.substr(0,e+1)}function h$jsstringIntercalate(b,c){for(var d=[],e=0;c.f===h$ghczmprimZCGHCziTypesziZC_con_e;)e&&(d[e++]=b),d[e++]=c.d1.d1,c=c.d2;return d.join("")}
function h$jsstringIntersperse(b,c){var d=0,e=c.length,f=0,g=[];if(65536<=b){var h=(b-65536>>>10)+56320;for(b=(b&1023)+55296;f<e;){d&&(g[d++]=h,g[d++]=b);var k=c.charCodeAt(f++);g[d++]=k;56319===(k|1023)&&(g[d++]=c.charCodeAt(f++))}}else for(;f<e;)d&&(g[d++]=b),k=c.charCodeAt(f++),g[d++]=k,56319===(k|1023)&&(g[d++]=c.charCodeAt(f++));return h$jsstringConvertArray(g)}function h$jsstringConcat(b){for(var c=[],d=0;b.f===h$ghczmprimZCGHCziTypesziZC_con_e;)c[d++]=b.d1.d1,b=b.d2;return c.join("")}
var h$jsstringStripPrefix,h$jsstringStripSuffix,h$jsstringIsPrefixOf,h$jsstringIsSuffixOf,h$jsstringIsInfixOf;
String.prototype.startsWith?(h$jsstringStripPrefix=function(b,c){return c.startsWith(b)?h$c1(h$baseZCGHCziBaseziJust_con_e,h$c1(h$ghcjszmprimZCGHCJSziPrimziJSVal_con_e,c.substr(b.length))):h$baseZCGHCziBaseziNothing},h$jsstringIsPrefixOf=function(b,c){return c.startsWith(b)}):(h$jsstringStripPrefix=function(b,c){return 0===c.indexOf(b)?h$c1(h$baseZCGHCziBaseziJust_con_e,h$c1(h$ghcjszmprimZCGHCJSziPrimziJSVal_con_e,c.substr(b.length))):h$baseZCGHCziBaseziNothing},h$jsstringIsPrefixOf=function(b,c){return 0===
c.indexOf(b)});
String.prototype.endsWith?(h$jsstringStripSuffix=function(b,c){return c.endsWith(b)?h$c1(h$baseZCGHCziBaseziJust_con_e,h$c1(h$ghcjszmprimZCGHCJSziPrimziJSVal_con_e,c.substr(0,c.length-b.length))):h$baseZCGHCziBaseziNothing},h$jsstringIsSuffixOf=function(b,c){return c.endsWith(b)}):(h$jsstringStripSuffix=function(b,c){var d=c.lastIndexOf(b);b=c.length-b.length;return-1!==d&&d===b?h$c1(h$baseZCGHCziBaseziJust_con_e,h$c1(h$ghcjszmprimZCGHCJSziPrimziJSVal_con_e,c.substr(0,b))):h$baseZCGHCziBaseziNothing},h$jsstringIsSuffixOf=
function(b,c){var d=c.lastIndexOf(b);return-1!==d&&d===c.length-b.length});h$jsstringIsInfixOf=String.prototype.includes?function(b,c){return c.includes(b)}:function(b,c){return-1!==c.indexOf(b)};
function h$jsstringCommonPrefixes(b,c){var d=b.length,e=c.length,f=0,g=d<=e?d:e;if(0===d||0===e||b.charCodeAt(0)!==c.charCodeAt(0))return h$baseZCGHCziBaseziNothing;for(;++f<g;){var h=b.charCodeAt(f);if(h!==c.charCodeAt(f)){57343===(h|1023)&&f--;break}}return 0===f?h$baseZCGHCziBaseziNothing:h$c1(h$baseZCGHCziBaseziJust_con_e,h$c3(h$ghczmprimZCGHCziTupleziZLz2cUz2cUZR_con_e,h$c1(h$ghcjszmprimZCGHCJSziPrimziJSVal_con_e,f===d?b:f===e?c:b.substr(0,f)),f===d?h$jsstringEmpty:h$c1(h$ghcjszmprimZCGHCJSziPrimziJSVal_con_e,
b.substr(f)),f===e?h$jsstringEmpty:h$c1(h$ghcjszmprimZCGHCJSziPrimziJSVal_con_e,c.substr(f))))}function h$jsstringBreakOn(b,c){b=c.indexOf(b);if(-1===b)return h$ret1="",c;if(0===b)return h$ret1=c,"";h$ret1=c.substr(b);return c.substr(0,b)}function h$jsstringBreakOnEnd(b,c){var d=c.lastIndexOf(b);if(-1===d)return h$ret1=c,"";d+=b.length;h$ret1=c.substr(d);return c.substr(0,d)}
function h$jsstringBreakOnAll1(b,c,d){b=d.indexOf(c,b);if(0===b)return h$ret1="",h$ret2=d,c.length;if(-1===b)return h$ret2=h$ret1=null,-1;h$ret1=d.substr(0,b);h$ret2=d.substr(b);return b+c.length}
function h$jsstringBreakOnAll(b,c){for(var d=[],e=0,f=0,g=h$ghczmprimZCGHCziTypesziZMZN,h=b.length;;){f=c.indexOf(b,f);if(-1===f)break;d[e++]=h$c2(h$ghczmprimZCGHCziTupleziZLz2cUZR_con_e,h$c1(h$ghcjszmprimZCGHCJSziPrimziJSVal_con_e,c.substr(0,f)),h$c1(h$ghcjszmprimZCGHCJSziPrimziJSVal_con_e,c.substr(f)));f+=h}for(;0<=--e;)g=h$c2(h$ghczmprimZCGHCziTypesziZC_con_e,d[e],g);return g}
function h$jsstringSplitOn1(b,c,d){var e=d.indexOf(c,b);if(-1===e)return h$ret1=null,-1;h$ret1=e==b?"":d.substr(b,e-b);return e+c.length}function h$jsstringSplitOn(b,c){b=c.split(b);c=h$ghczmprimZCGHCziTypesziZMZN;for(var d=b.length;0<=--d;)c=h$c2(h$ghczmprimZCGHCziTypesziZC_con_e,h$c1(h$ghcjszmprimZCGHCJSziPrimziJSVal_con_e,b[d]),c);return c}
function h$jsstringWords1(b,c){var d,e=c.length;if(b>=e)return-1;do if(b>=e)return-1;while(h$isSpace(c.charCodeAt(b++)));for(d=b-1;b<e;)if(h$isSpace(c.charCodeAt(b++)))return h$ret1=c=1>=b-d?"":c.substr(d,b-d-1),b;if(d<e)return h$ret1=c=0===d?c:c.substr(d),b;h$ret1=null;return-1}
function h$jsstringWords(b){var c=null,d=0,e=-1,f=0,g=b.length,h=h$ghczmprimZCGHCziTypesziZMZN;a:for(;f<g;){do if(f>=g){e=f;break a}while(h$isSpace(b.charCodeAt(f++)));for(e=f-1;f<g;)if(h$isSpace(b.charCodeAt(f++))){e=1>=f-e?h$jsstringEmpty:h$c1(h$ghcjszmprimZCGHCJSziPrimziJSVal_con_e,b.substr(e,f-e-1));d?c[d++]=e:(c=[e],d=1);e=f;break}}-1!==e&&e<g&&(e=h$c1(h$ghcjszmprimZCGHCJSziPrimziJSVal_con_e,0===e?b:b.substr(e)),d?c[d++]=e:(c=[e],d=1));for(;0<=--d;)h=h$c2(h$ghczmprimZCGHCziTypesziZC_con_e,c[d],
h);return h}function h$jsstringLines1(b,c){var d=b,e=c.length;if(b>=e)return-1;for(;d<e;)if(10===c.charCodeAt(d++)){if(0<b&&b===e-1)return-1;h$ret1=1>=d-b?"":c.substr(b,d-b-1);return d}h$ret1=c.substr(b);return d}
function h$jsstringLines(b){var c=null,d=0,e=0,f=b.length,g=h$ghczmprimZCGHCziTypesziZMZN;if(0===f)return h$ghczmprimZCGHCziTypesziZMZN;a:for(;;){var h=d;do if(d>=f)break a;while(10!==b.charCodeAt(d++));h=1>=d-h?h$jsstringEmpty:h$c1(h$ghcjszmprimZCGHCJSziPrimziJSVal_con_e,b.substr(h,d-h-1));e?c[e++]=h:(c=[h],e=1)}h<f&&(h=h$c1(h$ghcjszmprimZCGHCJSziPrimziJSVal_con_e,b.substr(h)),e?c[e++]=h:(c=[h],e=1));for(;0<=--e;)g=h$c2(h$ghczmprimZCGHCziTypesziZC_con_e,c[e],g);return g}
function h$jsstringGroup(b){var c=b.length;if(0===c)return h$ghczmprimZCGHCziTypesziZMZN;var d=c-1,e=c,f=h$ghczmprimZCGHCziTypesziZMZN,g=b.charCodeAt(d--);for(57343===(g|1023)&&(g=(b.charCodeAt(d--)-55296<<10)+g-9216);0<=d;){c=d;var h=b.charCodeAt(d--);57343===(h|1023)&&(h=(b.charCodeAt(d--)-55296<<10)+h-9216);h!=g&&(g=h,f=h$c2(h$ghczmprimZCGHCziTypesziZC_con_e,h$c1(h$ghcjszmprimZCGHCJSziPrimziJSVal_con_e,b.substr(c+1,e-c)),f),e=c)}return h$c2(h$ghczmprimZCGHCziTypesziZC_con_e,h$c1(h$ghcjszmprimZCGHCJSziPrimziJSVal_con_e,
b.substr(0,e+1)),f)}function h$jsstringChunksOf1(b,c,d){var e=c,f=0,g=d.length;if(0>=b||0===g||c>=g)return-1;for(;++e<g&&++f<b;){var h=d.charCodeAt(e);56319===(h|1023)&&++e}h$ret1=e>=g&&c===f?d:d.substr(c,e-c);return e}
function h$jsstringChunksOf(b,c){var d=c.length;if(0===d||0>=b)return h$ghczmprimZCGHCziTypesziZMZN;if(d<=b)return h$c2(h$ghczmprimZCGHCziTypesziZC_con_e,h$c1(h$ghcjszmprimZCGHCJSziPrimziJSVal_con_e,c),h$ghczmprimZCGHCziTypesziZMZN);for(var e=[],f=0,g,h,k=0,l,m=h$ghczmprimZCGHCziTypesziZMZN;k<d;){g=k;for(l=0;k<d&&++l<=b;)h=c.charCodeAt(k++),56319===(h|1023)&&++k;l&&(e[f++]=c.substr(g,k-g))}for(;0<=--f;)m=h$c2(h$ghczmprimZCGHCziTypesziZC_con_e,h$c1(h$ghcjszmprimZCGHCJSziPrimziJSVal_con_e,e[f]),m);
return m}function h$jsstringCount(b,c){for(var d=0,e=0,f=b.length,g=c.length;d<g;){d=c.indexOf(b,d);if(-1===d)break;e++;d+=f}return e}function h$jsstringReplicate(b,c){if(0===b||""==c)return"";if(1===b)return c;var d="";do b&1&&(d+=c),c+=c,b>>=1;while(1<b);return d+c}var h$jsstringReverse;
h$jsstringReverse=Array.from?function(b){return Array.from(b).reverse().join("")}:function(b){for(var c=b.length,d=[],e=0,f=0,g,h="";f<c;)g=b.charCodeAt(f),56319===(g|1023)?(d[f]=b.charCodeAt(f+1),d[f+1]=g,f+=2):d[f++]=g,6E4<f-e&&(h=String.fromCharCode.apply(null,d.reverse())+h,e=-f,d=[]);return 0===f?h:String.fromCharCode.apply(null,d.reverse())+h};
function h$jsstringUnpack(b){for(var c=h$ghczmprimZCGHCziTypesziZMZN,d=b.length-1,e;0<=d;)e=b.charCodeAt(d--),57343===(e|1023)&&(e=(b.charCodeAt(d--)-55296<<10)+e-9216),c=h$c2(h$ghczmprimZCGHCziTypesziZC_con_e,e,c);return c}function h$jsstringDecInteger(b){return b.f===h$integerzmgmpZCGHCziIntegerziTypeziSzh_con_e?""+b.d1:b.f===h$integerzmgmpZCGHCziIntegerziTypeziJpzh_con_e?h$ghcjsbn_showBase(b.d1,10):"-"+h$ghcjsbn_showBase(b.d1,10)}
function h$jsstringDecI64(b,c){var d=0>c?c+4294967296:c;if(0>b){if(-1===b)return""+(d-4294967296);d=4294967296-d;b=-1-b;var e=967296*b;c=(d+e)%1E6;b=4294*b+Math.floor((e+d-c)/1E6);return"-"+b+h$jsstringDecIPadded6(c)}if(0===b)return""+d;e=967296*b;c=(d+e)%1E6;b=4294*b+Math.floor((e+d-c)/1E6);return""+b+h$jsstringDecIPadded6(c)}
function h$jsstringDecW64(b,c){c=0>c?c+4294967296:c;if(0===b)return""+c;b=0>b?b+4294967296:b;var d=967296*b,e=(c+d)%1E6;return""+(4294*b+Math.floor((d+c-e)/1E6))+h$jsstringDecIPadded6(e)}function h$jsstringHexInteger(b){return b.f===h$integerzmgmpZCGHCziIntegerziTypeziSzh_con_e?""+b.d1:h$ghcjsbn_showBase(b.d1,16)}function h$jsstringHexI64(b,c){c=0>c?c+4294967296:c;return 0===b?c.toString(16):(0>b?b+4294967296:b).toString(16)+h$jsstringHexIPadded8(c)}
function h$jsstringHexW64(b,c){c=0>c?c+4294967296:c;return 0===b?c.toString(16):(0>b?b+4294967296:b).toString(16)+h$jsstringHexIPadded8(c)}function h$jsstringDecIPadded9(b){return 0===b?"000000000":(1E8<=b?"":1E7<=b?"0":1E6<=b?"00":1E5<=b?"000":1E4<=b?"0000":1E3<=b?"00000":100<=b?"000000":10<=b?"0000000":"00000000")+b}function h$jsstringDecIPadded6(b){return 0===b?"000000":(1E5<=b?"":1E4<=b?"0":1E3<=b?"00":100<=b?"000":10<=b?"0000":"00000")+b}
function h$jsstringHexIPadded8(b){return 0===b?"00000000":(268435456<=b?"":16777216<=b?"0":1048576<=b?"00":65536<=b?"000":4096<=b?"0000":256<=b?"00000":16<=b?"000000":"0000000")+b.toString(16)}function h$jsstringZeroes(b){switch(b&7){case 0:var c="";break;case 1:c="0";break;case 2:c="00";break;case 3:c="000";break;case 4:c="0000";break;case 5:c="00000";break;case 6:c="000000";break;case 7:c="0000000"}for(b>>=3;0<b;b--)c+="00000000";return c}
function h$jsstringDoubleToFixed(b,c){if(0<=b){if(1E21>Math.abs(c)){var d=c.toFixed(Math.min(20,b));20<b&&(d+=h$jsstringZeroes(b-20));return d}d=c.toExponential();var e=d.indexOf("e");c=d.indexOf(".");var f=parseInt(d.substr(e+1));return d.substring(0,c)+d.substring(c,e)+h$jsstringZeroes(c-e+f)+(0<b?"."+h$jsstringZeroes(b):"")}d=Math.abs(c).toExponential();e=d.indexOf("e");f=parseInt(d.substr(e+1));b=0>c?"-":"";d=d.substr(0,1)+d.substring(2,e);return 0<=f?f>d.length?b+d+h$jsstringZeroes(d.length-
f-1)+".0":b+d.substr(0,f+1)+"."+d.substr(f+1):b+"0."+h$jsstringZeroes(-f-1)+d}function h$jsstringDoubleToExponent(b,c){c=-1===b?c.toExponential().replace("+",""):c.toExponential(Math.max(1,Math.min(20,b))).replace("+","");-1===c.indexOf(".")&&(c=c.replace("e",".0e"));20<b&&(c=c.replace("e",h$jsstringZeroes(b-20)+"e"));return c}
function h$jsstringDoubleGeneric(b,c){c=-1===b?c.toString(10).replace("+",""):c.toPrecision(Math.max(b+1,1)).replace("+","");0!==b&&-1===c.indexOf(".")&&(c=-1!==c.indexOf("e")?c.replace("e",".0e"):c+".0");return c}function h$jsstringAppend(b,c){return b+c}function h$jsstringCompare(b,c){return b<c?-1:b>c?1:0}function h$jsstringUnlines(b){for(var c="";b.f===h$ghczmprimZCGHCziTypesziZC_con_e;)c=c+b.d1.d1+"\n",b=b.d2;return c}
function h$jsstringUnwords(b){if(b.f===h$ghczmprimZCGHCziTypesziZMZN_con_e)return"";var c=b.d1.d1;for(b=b.d2;b.f===h$ghczmprimZCGHCziTypesziZC_con_e;)c=c+" "+b.d1.d1,b=b.d2;return c}function h$jsstringReplace(b,c,d){var e=d.replace(b,c,"g");-1!==e.indexOf(b)&&(e=d.split(b).join(c));return e}function h$jsstringReplicateChar(b,c){return h$jsstringReplicate(b,h$jsstringSingleton(c))}function h$jsstringIsInteger(b){return/^-?\d+$/.test(b)}function h$jsstringIsNatural(b){return/^\d+$/.test(b)}
function h$jsstringReadInt(b){if(!/^-?\d+/.test(b))return null;b=parseInt(b,10);var c=b|0;return b===c?c:null}function h$jsstringLenientReadInt(b){b=parseInt(b,10);var c=b|0;return b===c?c:null}function h$jsstringReadWord(b){if(!/^\d+/.test(b))return null;b=parseInt(b,10);var c=b|0;return 0>c?b===c+2147483648?c:null:b===c?c:null}function h$jsstringReadDouble(b){return parseFloat(b,10)}function h$jsstringLenientReadDouble(b){return parseFloat(b,10)}
function h$jsstringReadInteger(b){return/^(-)?\d+$/.test(b)?9>=b.length?h$c1(h$integerzmgmpZCGHCziIntegerziTypeziSzh_con_e,parseInt(b,10)):h$ghcjsbn_readInteger(b):null}function h$jsstringReadInt64(b){return/^(-)?\d+$/.test(b)?45===b.charCodeAt(0)?h$jsstringReadValue64(b,1,!0):h$jsstringReadValue64(b,0,!1):h$ret2=h$ret1=0}function h$jsstringReadWord64(b){return/^\d+$/.test(b)?h$jsstringReadValue64(b,0,!1):h$ret2=h$ret1=0}var h$jsstringLongs=null;
function h$jsstringReadValue64(b,c,d){for(var e=b.length;c<e&&48===b.charCodeAt(c);)c++;if(c>=e)return h$ret2=h$ret1=0,1;if(null===h$jsstringLongs){h$jsstringLongs=[];for(var f=10;1E9>=f;f*=10)h$jsstringLongs.push(goog.math.Long.fromInt(f))}f=e-c;if(10>f&&!d)return h$ret1=0,h$ret2=parseInt(b.substr(c),10),1;c=goog.math.Long.fromInt(parseInt(b.substr(f,9),10));for(f+=9;f<e;)c=c.multiply(h$jsstringLongs[Math.min(e-f-1,8)]).add(goog.math.Long.fromInt(parseInt(b.substr(f,9),10))),f+=9;d&&(c=c.negate());
h$ret1=c.getHighBits();h$ret2=c.getLowBits();return 1}function h$jsstringExecRE(b,c,d){d.lastIndex=b;b=d.exec(c);if(null===b)return-1;c=[];for(var e=1,f=h$ghczmprimZCGHCziTypesziZMZN;;){d=b[e];if("undefined"===typeof d)break;c[e-1]=d;e++}for(--e;0<=--e;)f=h$c2(h$ghczmprimZCGHCziTypesziZC_con_e,h$c1(h$ghcjszmprimZCGHCJSziPrimziJSVal_con_e,c[e]),f);h$ret1=b[0];h$ret2=f;return b.index}function h$jsstringReplaceRE(b,c,d){return d.replace(b,c)}
function h$jsstringSplitRE(b,c,d){c.lastIndex=e;var e=(0>b?d.split(c):d.split(c,b)).length;for(b=h$ghczmprimZCGHCziTypesziZMZN;0<=--e;)b=h$c2(h$ghczmprimZCGHCziTypesziZC_con_e,h$c1(h$ghcjszmprimZCGHCJSziPrimziJSVal_con_e,a[e]),b);return b}
function h$jsstringRawChunksOf(b,c){var d=c.length;if(0===d)return h$ghczmprimZCGHCziTypesziZMZN;if(d<=b)return h$c2(h$ghczmprimZCGHCziTypesziZC_con_e,h$c1(h$ghcjszmprimZCGHCJSziPrimziJSVal_con_e,c),h$ghczmprimZCGHCziTypesziZMZN);d=h$ghczmprimZCGHCziTypesziZMZN;for(var e=ls-b;0<=e;e-=b)d=h$c2(h$ghczmprimZCGHCziTypesziZC_con_e,h$c1(h$ghcjszmprimZCGHCJSziPrimziJSVal_con_e,c.substr(e,e+b)),d);return d}
function h$jsstringRawSplitAt(b,c){return 0===b?h$c2(h$ghczmprimZCGHCziTupleziZLz2cUZR_con_e,h$jsstringEmpty,h$c1(h$ghcjszmprimZCGHCJSziPrimziJSVal_con_e,c)):b>=c.length?h$c2(h$ghczmprimZCGHCziTupleziZLz2cUZR_con_e,h$c1(h$ghcjszmprimZCGHCJSziPrimziJSVal_con_e,c),h$jsstringEmpty):h$c2(h$ghczmprimZCGHCziTupleziZLz2cUZR_con_e,h$c1(h$ghcjszmprimZCGHCJSziPrimziJSVal_con_e,c.substr(0,b)),h$c1(h$ghcjszmprimZCGHCJSziPrimziJSVal_con_e,c.substr(b)))}
function h$foreignListProps(b){if("undefined"===typeof b||null===b)return null;throw"h$foreignListProps";}function h$textToString(b,c,d){var e=[];d=c+d;var f=0;b=b.u1;for(var g="";c<d;c++){var h=b[c];e[f++]=h;6E4===f&&(g+=String.fromCharCode.apply(this,e),f=0,e=[])}return g+String.fromCharCode.apply(this,e)}function h$textFromString(b){for(var c=b.length,d=h$newByteArray(2*c),e=d.u1,f=c-1;0<=f;f--)e[f]=b.charCodeAt(f);h$ret1=c;return d}
function h$lazyTextToString(b){for(var c="";2===b.f.a;){var d=b;c+=h$textToString(d.d1,d.d2.d1,d.d2.d2);b=b.d2.d3}return c}function h$safeTextFromString(b){return"string"!==typeof b?(h$ret1=0,null):h$textFromString(b)}function h$allProps(b){var c=[],d=0,e;for(e in b)c[d++]=e;return c}function h$listAllProps(b){var c=h$ghczmprimZCGHCziTypesziZMZN,d;for(d in b)c=h$c2(h$ghczmprimZCGHCziTypesziZC_con_e,h$c1(h$ghcjszmprimZCGHCJSziPrimziJSVal_con_e,d),c);return c}
function h$listAssocs(b){var c=h$ghczmprimZCGHCziTypesziZMZN,d;for(d in b)c=h$c2(h$ghczmprimZCGHCziTypesziZC_con_e,h$c2(h$ghczmprimZCGHCziTupleziZLz2cUZR_con_e,h$c1(h$ghcjszmprimZCGHCJSziPrimziJSVal_con_e,d),h$c1(h$ghcjszmprimZCGHCJSziPrimziJSVal_con_e,b[d])),c);return c}function h$isNumber(b){return"number"===typeof b}function h$isObject(b){return"object"===typeof b}function h$isString(b){return"string"===typeof b}function h$isSymbol(b){return"symbol"===typeof b}
function h$isBoolean(b){return"boolean"===typeof b}function h$isFunction(b){return"function"===typeof b}function h$jsTypeOf(b){b=typeof b;return"undefined"===b?0:"object"===b?1:"boolean"===b?2:"number"===b?3:"string"===b?4:"symbol"===b?5:"function"===b?6:7}function h$jsonTypeOf(b){return b instanceof Object?"[object Array]"==Object.prototype.toString.call(b)?5:b?6:0:null==b?0:"number"==typeof b?h$isInteger(b)?1:2:"boolean"==typeof b?3:4}
function h$sendXHR(b,c,d){b.addEventListener("error",function(){d(2)});b.addEventListener("abort",function(){d(1)});b.addEventListener("load",function(){d(0)});c?b.send(c):b.send()}goog.crypt={};goog.crypt.Hash=function(){this.blockSize=-1};goog.crypt.Hash.prototype.reset=goog.abstractMethod;goog.crypt.Hash.prototype.update=goog.abstractMethod;goog.crypt.Hash.prototype.digest=goog.abstractMethod;
goog.crypt.Md5=function(){goog.crypt.Hash.call(this);this.blockSize=64;this.chain_=Array(4);this.block_=Array(this.blockSize);this.totalLength_=this.blockLength_=0;this.reset()};goog.inherits(goog.crypt.Md5,goog.crypt.Hash);goog.crypt.Md5.prototype.reset=function(){this.chain_[0]=1732584193;this.chain_[1]=4023233417;this.chain_[2]=2562383102;this.chain_[3]=271733878;this.totalLength_=this.blockLength_=0};
goog.crypt.Md5.prototype.compress_=function(b,c){c||(c=0);var d=Array(16);if(goog.isString(b))for(var e=0;16>e;++e)d[e]=b.charCodeAt(c++)|b.charCodeAt(c++)<<8|b.charCodeAt(c++)<<16|b.charCodeAt(c++)<<24;else for(e=0;16>e;++e)d[e]=b[c++]|b[c++]<<8|b[c++]<<16|b[c++]<<24;b=this.chain_[0];c=this.chain_[1];e=this.chain_[2];var f=this.chain_[3];var g=b+(f^c&(e^f))+d[0]+3614090360&4294967295;b=c+(g<<7&4294967295|g>>>25);g=f+(e^b&(c^e))+d[1]+3905402710&4294967295;f=b+(g<<12&4294967295|g>>>20);g=e+(c^f&(b^
c))+d[2]+606105819&4294967295;e=f+(g<<17&4294967295|g>>>15);g=c+(b^e&(f^b))+d[3]+3250441966&4294967295;c=e+(g<<22&4294967295|g>>>10);g=b+(f^c&(e^f))+d[4]+4118548399&4294967295;b=c+(g<<7&4294967295|g>>>25);g=f+(e^b&(c^e))+d[5]+1200080426&4294967295;f=b+(g<<12&4294967295|g>>>20);g=e+(c^f&(b^c))+d[6]+2821735955&4294967295;e=f+(g<<17&4294967295|g>>>15);g=c+(b^e&(f^b))+d[7]+4249261313&4294967295;c=e+(g<<22&4294967295|g>>>10);g=b+(f^c&(e^f))+d[8]+1770035416&4294967295;b=c+(g<<7&4294967295|g>>>25);g=f+(e^
b&(c^e))+d[9]+2336552879&4294967295;f=b+(g<<12&4294967295|g>>>20);g=e+(c^f&(b^c))+d[10]+4294925233&4294967295;e=f+(g<<17&4294967295|g>>>15);g=c+(b^e&(f^b))+d[11]+2304563134&4294967295;c=e+(g<<22&4294967295|g>>>10);g=b+(f^c&(e^f))+d[12]+1804603682&4294967295;b=c+(g<<7&4294967295|g>>>25);g=f+(e^b&(c^e))+d[13]+4254626195&4294967295;f=b+(g<<12&4294967295|g>>>20);g=e+(c^f&(b^c))+d[14]+2792965006&4294967295;e=f+(g<<17&4294967295|g>>>15);g=c+(b^e&(f^b))+d[15]+1236535329&4294967295;c=e+(g<<22&4294967295|
g>>>10);g=b+(e^f&(c^e))+d[1]+4129170786&4294967295;b=c+(g<<5&4294967295|g>>>27);g=f+(c^e&(b^c))+d[6]+3225465664&4294967295;f=b+(g<<9&4294967295|g>>>23);g=e+(b^c&(f^b))+d[11]+643717713&4294967295;e=f+(g<<14&4294967295|g>>>18);g=c+(f^b&(e^f))+d[0]+3921069994&4294967295;c=e+(g<<20&4294967295|g>>>12);g=b+(e^f&(c^e))+d[5]+3593408605&4294967295;b=c+(g<<5&4294967295|g>>>27);g=f+(c^e&(b^c))+d[10]+38016083&4294967295;f=b+(g<<9&4294967295|g>>>23);g=e+(b^c&(f^b))+d[15]+3634488961&4294967295;e=f+(g<<14&4294967295|
g>>>18);g=c+(f^b&(e^f))+d[4]+3889429448&4294967295;c=e+(g<<20&4294967295|g>>>12);g=b+(e^f&(c^e))+d[9]+568446438&4294967295;b=c+(g<<5&4294967295|g>>>27);g=f+(c^e&(b^c))+d[14]+3275163606&4294967295;f=b+(g<<9&4294967295|g>>>23);g=e+(b^c&(f^b))+d[3]+4107603335&4294967295;e=f+(g<<14&4294967295|g>>>18);g=c+(f^b&(e^f))+d[8]+1163531501&4294967295;c=e+(g<<20&4294967295|g>>>12);g=b+(e^f&(c^e))+d[13]+2850285829&4294967295;b=c+(g<<5&4294967295|g>>>27);g=f+(c^e&(b^c))+d[2]+4243563512&4294967295;f=b+(g<<9&4294967295|
g>>>23);g=e+(b^c&(f^b))+d[7]+1735328473&4294967295;e=f+(g<<14&4294967295|g>>>18);g=c+(f^b&(e^f))+d[12]+2368359562&4294967295;c=e+(g<<20&4294967295|g>>>12);g=b+(c^e^f)+d[5]+4294588738&4294967295;b=c+(g<<4&4294967295|g>>>28);g=f+(b^c^e)+d[8]+2272392833&4294967295;f=b+(g<<11&4294967295|g>>>21);g=e+(f^b^c)+d[11]+1839030562&4294967295;e=f+(g<<16&4294967295|g>>>16);g=c+(e^f^b)+d[14]+4259657740&4294967295;c=e+(g<<23&4294967295|g>>>9);g=b+(c^e^f)+d[1]+2763975236&4294967295;b=c+(g<<4&4294967295|g>>>28);g=
f+(b^c^e)+d[4]+1272893353&4294967295;f=b+(g<<11&4294967295|g>>>21);g=e+(f^b^c)+d[7]+4139469664&4294967295;e=f+(g<<16&4294967295|g>>>16);g=c+(e^f^b)+d[10]+3200236656&4294967295;c=e+(g<<23&4294967295|g>>>9);g=b+(c^e^f)+d[13]+681279174&4294967295;b=c+(g<<4&4294967295|g>>>28);g=f+(b^c^e)+d[0]+3936430074&4294967295;f=b+(g<<11&4294967295|g>>>21);g=e+(f^b^c)+d[3]+3572445317&4294967295;e=f+(g<<16&4294967295|g>>>16);g=c+(e^f^b)+d[6]+76029189&4294967295;c=e+(g<<23&4294967295|g>>>9);g=b+(c^e^f)+d[9]+3654602809&
4294967295;b=c+(g<<4&4294967295|g>>>28);g=f+(b^c^e)+d[12]+3873151461&4294967295;f=b+(g<<11&4294967295|g>>>21);g=e+(f^b^c)+d[15]+530742520&4294967295;e=f+(g<<16&4294967295|g>>>16);g=c+(e^f^b)+d[2]+3299628645&4294967295;c=e+(g<<23&4294967295|g>>>9);g=b+(e^(c|~f))+d[0]+4096336452&4294967295;b=c+(g<<6&4294967295|g>>>26);g=f+(c^(b|~e))+d[7]+1126891415&4294967295;f=b+(g<<10&4294967295|g>>>22);g=e+(b^(f|~c))+d[14]+2878612391&4294967295;e=f+(g<<15&4294967295|g>>>17);g=c+(f^(e|~b))+d[5]+4237533241&4294967295;
c=e+(g<<21&4294967295|g>>>11);g=b+(e^(c|~f))+d[12]+1700485571&4294967295;b=c+(g<<6&4294967295|g>>>26);g=f+(c^(b|~e))+d[3]+2399980690&4294967295;f=b+(g<<10&4294967295|g>>>22);g=e+(b^(f|~c))+d[10]+4293915773&4294967295;e=f+(g<<15&4294967295|g>>>17);g=c+(f^(e|~b))+d[1]+2240044497&4294967295;c=e+(g<<21&4294967295|g>>>11);g=b+(e^(c|~f))+d[8]+1873313359&4294967295;b=c+(g<<6&4294967295|g>>>26);g=f+(c^(b|~e))+d[15]+4264355552&4294967295;f=b+(g<<10&4294967295|g>>>22);g=e+(b^(f|~c))+d[6]+2734768916&4294967295;
e=f+(g<<15&4294967295|g>>>17);g=c+(f^(e|~b))+d[13]+1309151649&4294967295;c=e+(g<<21&4294967295|g>>>11);g=b+(e^(c|~f))+d[4]+4149444226&4294967295;b=c+(g<<6&4294967295|g>>>26);g=f+(c^(b|~e))+d[11]+3174756917&4294967295;f=b+(g<<10&4294967295|g>>>22);g=e+(b^(f|~c))+d[2]+718787259&4294967295;e=f+(g<<15&4294967295|g>>>17);g=c+(f^(e|~b))+d[9]+3951481745&4294967295;this.chain_[0]=this.chain_[0]+b&4294967295;this.chain_[1]=this.chain_[1]+(e+(g<<21&4294967295|g>>>11))&4294967295;this.chain_[2]=this.chain_[2]+
e&4294967295;this.chain_[3]=this.chain_[3]+f&4294967295};goog.crypt.Md5.prototype.update=function(b,c){goog.isDef(c)||(c=b.length);for(var d=c-this.blockSize,e=this.block_,f=this.blockLength_,g=0;g<c;){if(0==f)for(;g<=d;)this.compress_(b,g),g+=this.blockSize;if(goog.isString(b))for(;g<c;){if(e[f++]=b.charCodeAt(g++),f==this.blockSize){this.compress_(e);f=0;break}}else for(;g<c;)if(e[f++]=b[g++],f==this.blockSize){this.compress_(e);f=0;break}}this.blockLength_=f;this.totalLength_+=c};
goog.crypt.Md5.prototype.digest=function(){var b=Array((56>this.blockLength_?this.blockSize:2*this.blockSize)-this.blockLength_);b[0]=128;for(var c=1;c<b.length-8;++c)b[c]=0;var d=8*this.totalLength_;for(c=b.length-8;c<b.length;++c)b[c]=d&255,d/=256;this.update(b);b=Array(16);for(c=d=0;4>c;++c)for(var e=0;32>e;e+=8)b[d++]=this.chain_[c]>>>e&255;return b};function h$base_access(b,c,d,e){h$isNode?h$fs.stat(fd,function(b,c){b?h$handleErrnoC(b,-1,0,e):e(d&c.mode)}):h$unsupported(-1,e)}
function h$base_chmod(b,c,d,e){h$isNode?h$fs.chmod(h$decodeUtf8z(b,c),d,function(b){h$handleErrnoC(b,-1,0,e)}):h$unsupported(-1,e)}function h$base_close(b,c){var d=h$base_fds[b];d&&d.close?d.close(b,d,c):(h$errno=22,c(-1))}function h$base_dup(b,c,d){throw"h$base_dup";}function h$base_dup2(b,c){throw"h$base_dup2";}function h$base_fstat(b,c,d,e){h$isNode?h$fs.fstat(b,function(b,g){b?h$handlErrnoC(b,-1,0,e):(h$base_fillStat(g,c,d),e(0))}):h$unsupported(-1,e)}
function h$base_isatty(b){if(h$isNode){if(0===b)return process.stdin.isTTY?1:0;if(1===b)return process.stdout.isTTY?1:0;if(2===b)return process.stderr.isTTY?1:0}return 1===b||2===b?1:0}
function h$base_lseek(b,c,d,e,f){if(h$isNode){var g=goog.math.Long.fromBits(d,c),h=h$base_fds[b];if(h)switch(e){case 0:h.pos=g.toNumber();f(g.getHighBits(),g.getLowBits());break;case 1:h.pos+=g.toNumber();var k=goog.math.Long.fromNumber(h.pos);f(k.getHighBits(),k.getLowBits());break;case 2:h$fs.fstat(b,function(b,c){b?(h$setErrno(b),f(-1,-1)):(h.pos=c.size+g.toNumber(),k=goog.math.Long.fromNumber(h.pos),f(k.getHighBits(),k.getLowBits()))});break;default:h$errno=22,f(-1,-1)}else h$errno=CONST_BADF,
f(-1,-1)}else h$unsupported(),f(-1,-1)}function h$base_lstat(b,c,d,e,f){h$isNode?h$fs.lstat(h$decodeUtf8z(b,c),function(b,c){b?h$handleErrnoC(b,-1,0,f):(h$base_fillStat(c,d,e),f(0))}):h$unsupported(-1,f)}
function h$base_open(b,c,d,e,f){if(h$isNode){var g=h$decodeUtf8z(b,c);b=d&h$base_o_accmode;b=b===h$base_o_rdonly?h$processConstants.fs.O_RDONLY:b===h$base_o_wronly?h$processConstants.fs.O_WRONLY:h$processConstants.fs.O_RDWR;var h=d&h$base_o_append?-1:0;b=b|(d&h$base_o_trunc?h$processConstants.fs.O_TRUNC:0)|(d&h$base_o_creat?h$processConstants.fs.O_CREAT:0)|(d&h$base_o_excl?h$processConstants.fs.O_EXCL:0)|(d&h$base_o_append?h$processConstants.fs.O_APPEND:0);h$fs.open(g,b,e,function(b,c){if(b)h$handleErrnoC(b,
-1,0,f);else{var d=function(b){h$base_fds[c]={read:h$base_readFile,write:h$base_writeFile,close:h$base_closeFile,pos:b};f(c)};-1===h?h$fs.stat(g,function(b,c){b?h$handleErrnoC(b,-1,0,f):d(c.size)}):d(0)}})}else h$unsupported(-1,f)}function h$base_read(b,c,d,e,f){var g=h$base_fds[b];g&&g.read?g.read(b,g,c,d,e,f):(h$errno=22,f(-1))}function h$base_stat(b,c,d,e,f){h$isNode?h$fs.stat(h$decodeUtf8z(b,c),function(b,c){b?h$handlErrnoC(b,-1,0,f):(h$base_fillStat(c,d,e),f(0))}):h$unsupported(-1,f)}
function h$base_umask(b){return h$isNode?process.umask(b):0}function h$base_write(b,c,d,e,f){var g=h$base_fds[b];g&&g.write?g.write(b,g,c,d,e,f):(h$errno=22,f(-1))}function h$base_ftruncate(b,c,d,e){h$isNode?h$fs.ftruncate(b,goog.math.Long.fromBits(d,c).toNumber(),function(b){h$handleErrnoC(b,-1,0,e)}):h$unsupported(-1,e)}function h$base_unlink(b,c,d){h$isNode?h$fs.unlink(h$decodeUtf8z(b,c),function(b){h$handleErrnoC(b,-1,0,d)}):h$unsupported(-1,d)}
function h$base_getpid(){return h$isNode?process.pid:0}function h$base_link(b,c,d,e,f){h$isNode?h$fs.link(h$decodeUtf8z(b,c),h$decodeUtf8z(d,e),function(b){h$handleErrnoC(b,-1,0,f)}):h$unsupported(-1,f)}function h$base_mkfifo(b,c,d,e){throw"h$base_mkfifo";}function h$base_sigemptyset(b,c){return 0}function h$base_sigaddset(b,c,d){return 0}function h$base_sigprocmask(b,c,d,e,f){return 0}function h$base_tcgetattr(b,c,d){return 0}function h$base_tcsetattr(b,c,d,e){return 0}
function h$base_utime(b,c,d,e,f){h$isNode?h$fs.fstat(h$decodeUtf8z(b,c),function(b,c){if(b)h$handleErrnoC(b,0,-1,f);else{b=goog.math.Long.fromNumber(c.atime.getTime());var e=goog.math.Long.fromNumber(c.mtime.getTime());c=goog.math.Long.fromNumber(c.ctime.getTime());d.i3[0]=b.getHighBits();d.i3[1]=b.getLowBits();d.i3[2]=e.getHighBits();d.i3[3]=e.getLowBits();d.i3[4]=c.getHighBits();d.i3[5]=c.getLowBits();f(0)}}):h$unsupported(-1,f)}function h$base_waitpid(b,c,d,e,f){throw"h$base_waitpid";}
var h$base_o_rdonly=0,h$base_o_wronly=1,h$base_o_rdwr=2,h$base_o_accmode=3,h$base_o_append=8,h$base_o_creat=512,h$base_o_trunc=1024,h$base_o_excl=2048,h$base_o_noctty=131072,h$base_o_nonblock=4,h$base_o_binary=0;function h$base_c_s_isreg(b){return 1}function h$base_c_s_ischr(b){return 0}function h$base_c_s_isblk(b){return 0}function h$base_c_s_isdir(b){return 0}function h$base_c_s_isfifo(b){return 0}
function h$base_fillStat(b,c,d){if(d%4)throw"h$base_fillStat: not aligned";d>>=2;c.i3[d+0]=b.mode;var e=goog.math.Long.fromNumber(b.size);c.i3[d+1]=e.getHighBits();c.i3[d+2]=e.getLowBits();c.i3[d+3]=0;c.i3[d+4]=0;c.i3[d+5]=b.dev;e=goog.math.Long.fromNumber(b.ino);c.i3[d+6]=e.getHighBits();c.i3[d+7]=e.getLowBits();c.i3[d+8]=b.uid;c.i3[d+9]=b.gid}var h$base_sizeof_stat=40;function h$base_st_mtime(b,c){h$ret1=b.i3[(c>>2)+4];return b.i3[(c>>2)+3]}
function h$base_st_size(b,c){h$ret1=b.i3[(c>>2)+2];return b.i3[(c>>2)+1]}function h$base_st_mode(b,c){return b.i3[c>>2]}function h$base_st_dev(b,c){return b.i3[(c>>2)+5]}function h$base_st_ino(b,c){h$ret1=b.i3[(c>>2)+7];return b.i3[(c>>2)+6]}var h$base_echo=1,h$base_tcsanow=2,h$base_icanon=4,h$base_vmin=8,h$base_vtime=16,h$base_sigttou=0,h$base_sig_block=0,h$base_sig_setmask=0,h$base_f_getfl=0,h$base_f_setfl=0,h$base_f_setfd=0,h$base_fd_cloexec=0,h$base_sizeof_termios=4,h$base_sizeof_sigset_t=4;
function h$base_lflag(b,c){return 0}function h$base_poke_lflag(b,c,d){return 0}function h$base_ptr_c_cc(b,c){h$ret1=0;return h$newByteArray(8)}var h$base_default_buffer_size=32768;function h$base_c_s_issock(b){return 0}var h$base_SEEK_SET=0,h$base_SEEK_CUR=1,h$base_SEEK_END=2;function h$base_set_saved_termios(b,c,d){h$ret1=0;return null}function h$base_get_saved_termios(b){h$ret1=0;return null}function h$lockFile(b,c,d,e){return 0}function h$unlockFile(b){return 0}
var h$base_readStdin,h$base_writeStderr,h$base_writeStdout,h$base_closeStdin=null,h$base_closeStderr=null,h$base_closeStdout=null,h$base_readFile,h$base_writeFile,h$base_closeFile,h$base_stdin_waiting=new h$Queue,h$base_stdin_chunk={buf:null,pos:0,processing:!1},h$base_stdin_eof=!1,h$base_process_stdin=function(){var b=h$base_stdin_chunk,c=h$base_stdin_waiting;if(c.length()&&!b.processing){b.processing=!0;b.buf||(b.pos=0,b.buf=process.stdin.read());for(;b.buf&&c.length();){for(var d=c.dequeue(),e=
Math.min(b.buf.length-b.pos,d.n),f=0;f<e;f++)d.buf.u8[f+d.off]=b.buf[b.pos+f];b.pos+=e;d.c(e);b.pos>=b.buf.length&&(b.buf=null);!b.buf&&c.length()&&(b.pos=0,b.buf=process.stdin.read())}for(;h$base_stdin_eof&&c.length();)c.dequeue().c(0);b.processing=!1}};
if(h$isNode)h$base_closeFile=function(b,c,d){h$fs.close(b,function(c){delete h$base_fds[b];h$handleErrnoC(c,-1,0,d)})},h$base_readFile=function(b,c,d,e,f,g){var h="number"===typeof c.pos?c.pos:null;h$fs.read(b,new Buffer(f),0,f,h,function(b,f,h){if(b)h$setErrno(b),g(-1);else{for(b=f-1;0<=b;b--)d.u8[e+b]=h[b];"number"===typeof c.pos&&(c.pos+=f);g(f)}})},h$base_readStdin=function(b,c,d,e,f,g){h$base_stdin_waiting.enqueue({buf:d,off:e,n:f,c:g});h$base_process_stdin()},h$base_closeStdin=function(b,c,
d){d(0)},h$base_writeFile=function(b,c,d,e,f,g){for(var h="number"===typeof c.pos?c.pos:null,k=new Buffer(f),l=0;l<f;l++)k[l]=d.u8[l+e];"number"===typeof c.pos&&(c.pos+=f);h$fs.write(b,k,0,f,h,function(h,k){h?(h$setErrno(h),"number"===typeof c.pos&&(c.pos-=f),35===h$errno?setTimeout(function(){h$base_writeFile(b,c,d,e,f,g)},20):g(-1)):("number"===typeof c.pos&&(c.pos+=k-f),g(k))})},h$base_writeStdout=function(b,c,d,e,f,g){h$base_writeFile(1,c,d,e,f,g)},h$base_closeStdout=function(b,c,d){d(0)},h$base_writeStderr=
function(b,c,d,e,f,g){h$base_writeFile(2,c,d,e,f,g)},h$base_closeStderr=function(b,c,d){d(0)},process.stdin.on("readable",h$base_process_stdin),process.stdin.on("end",function(){h$base_stdin_eof=!0;h$base_process_stdin()});else if(h$isJsShell)h$base_readStdin=function(b,c,d,e,f,g){g(0)},h$base_writeStdout=function(b,c,d,e,f,g){putstr(h$decodeUtf8(d,f,e));g(f)},h$base_writeStderr=function(b,c,d,e,f,g){printErr(h$decodeUtf8(d,f,e));g(f)};else if(h$isJsCore){h$base_readStdin=function(b,c,d,e,f,g){g(0)};
var h$base_stdoutLeftover={f:print,val:null},h$base_stderrLeftover={f:debug,val:null},h$base_writeWithLeftover=function(b,c,d,e,f){b=h$decodeUtf8(b,c,d).split(/\r?\n/);if(1===b.length)b[0].length&&(f.val=null!==f.val?f.val+b[0]:b[0]);else{f.f((null!==f.val?f.val:"")+b[0]);for(d=1;d<b.length-1;d++)f.f(b[d]);f.val=b[b.length-1].length?b[b.length-1]:null}e(c)};h$base_writeStdout=function(b,c,d,e,f,g){h$base_writeWithLeftover(d,f,e,g,h$base_stdoutLeftover)};h$base_writeStderr=function(b,c,d,e,f,g){h$base_writeWithLeftover(d,
f,e,g,h$base_stderrLeftover)}}else h$base_readStdin=function(b,c,d,e,f,g){g(0)},h$base_writeStdout=function(b,c,d,e,f,g){console.log(h$decodeUtf8(d,f,e));g(f)},h$base_writeStderr=function(b,c,d,e,f,g){console.log(h$decodeUtf8(d,f,e));g(f)};
var h$base_stdin_fd={read:h$base_readStdin,close:h$base_closeStdin},h$base_stdout_fd={write:h$base_writeStdout,close:h$base_closeStdout},h$base_stderr_fd={write:h$base_writeStderr,close:h$base_closeStderr},h$base_fdN=-1,h$base_fds=[h$base_stdin_fd,h$base_stdout_fd,h$base_stderr_fd];function h$shutdownHaskellAndExit(b,c){h$exitProcess(b)}function h$rand(){return 32768*Math.random()&32767}function h$hsprimitive_memcpy(b,c,d,e,f,g,h){return h$primitive_memmove(b,c,d,e,f,h)}
function h$hsprimitive_memmove(b,c,d,e,f,g,h){if(0!==h)for(b=b.u8,e=e.u8,--h;0<=h;h--)b[c+h]=e[f+h]}function h$hsprimitive_memsetba_Word8(b,c,d,e){if(0<d)if(b.u8.fill)b.u8.fill(e,c,c+d);else for(var f=c;f<c+d;f++)b.u8[f]=e}function h$hsprimitive_memsetba_Word16(b,c,d,e){if(0<d)if(b.u1.fill)b.u1.fill(e,c,c+d);else for(var f=c;f<c+d;f++)b.u1[f]=e}function h$hsprimitive_memsetba_Word32(b,c,d,e){if(0<d)if(b.i3.fill)b.i3.fill(e,c,c+d);else for(var f=c;f<c+d;f++)b.i3[f]=e}
function h$hsprimitive_memsetba_Word(b,c,d,e){if(0<d)if(b.i3.fill)b.i3.fill(e,c,c+d);else for(var f=c;f<c+d;f++)b.i3[f]=e}function h$hsprimitive_memsetba_Float(b,c,d,e){if(0<d)if(b.f3.fill)b.f3.fill(e,c,c+d);else for(var f=c;f<c+d;f++)b.f3[f]=e}function h$hsprimitive_memsetba_Double(b,c,d,e){if(0<d)if(b.f6.fill)b.f6.fill(e,c,c+d);else for(var f=c;f<c+d;f++)b.f6[f]=e}function h$hsprimitive_memsetba_Char(b,c,d,e){if(0<d)if(b.i3.fill)b.i3.fill(e,c,c+d);else for(var f=c;f<c+d;f++)b.i3[f]=e}
function h$hsprimitive_memset_Word8(b,c,d,e,f){c=(c>>0)+d;if(0<e)if(b.u8.fill)b.u8.fill(f,c,c+e);else for(d=c;d<c+e;d++)b.u8[d]=f}function h$hsprimitive_memset_Word16(b,c,d,e,f){c=(c>>1)+d;if(0<e)if(b.u1.fill)b.u1.fill(f,c,c+e);else for(d=c;d<c+e;d++)b.u1[d]=f}function h$hsprimitive_memset_Word32(b,c,d,e,f){c=(c>>2)+d;if(0<e)if(b.i3.fill)b.i3.fill(f,c,c+e);else for(d=c;d<c+e;d++)b.i3[d]=f}
function h$hsprimitive_memset_Word(b,c,d,e,f){c=(c>>2)+d;if(0<e)if(b.i3.fill)b.i3.fill(f,c,c+e);else for(d=c;d<c+e;d++)b.i3[d]=f}function h$hsprimitive_memset_Float(b,c,d,e,f){c=(c>>2)+d;if(0<e)if(b.f3.fill)b.f3.fill(f,c,c+e);else for(d=c;d<c+e;d++)b.f3[d]=f}function h$hsprimitive_memset_Double(b,c,d,e,f){c=(c>>3)+d;if(0<e)if(b.f6.fill)b.f6.fill(f,c,c+e);else for(d=c;d<c+e;d++)b.f6[d]=f}
function h$hsprimitive_memset_Char(b,c,d,e,f){c=(c>>2)+d;if(0<e)if(b.i3.fill)b.i3.fill(f,c,c+e);else for(d=c;d<c+e;d++)b.i3[d]=f}function h$hsprimitive_memsetba_Word64(b,c,d,e,f){h$hsprimitive_memset_Word64(b,0,c,d,e,f)}function h$hsprimitive_memset_Word64(b,c,d,e,f,g){c=(c>>3)+d;if(0<e)for(b=b.i3,d=0;d<e;d++){var h=c+d<<1;b[h]=f;b[h+1]=g}}function h$hsprimitive_memset_Ptr(b,c,d,e,f,g){if(0<e){b.arr||(b.arr=[]);b=b.arr;for(var h=0;h<e;h++)b[c+(d+h<<2)]=[f,g]}}
function h$get_current_timezone_seconds(b,c,d,e,f){b=new Date(1E3*b);var g=new Date,h=new Date(g.getFullYear(),0,1);g=new Date(g.getFullYear(),6,1);h=Math.max(h.getTimezoneOffset(),g.getTimezoneOffset());h=b.getTimezoneOffset()<h;b=b.getTimezoneOffset();c.dv.setInt32(d,h?1:0,!0);e.arr||(e.arr=[]);e.arr[f]=[h$encodeUtf8("UTC"+(0>b?"+"+b/-60:""+b/-60)),0];return-60*b|0}
function h$clock_gettime(b,c,d){b=d>>2;d=Date.now?Date.now():(new Date).getTime();var e=Math.floor(d/1E3);c.i3[b]=e|0;c.i3[b+1]=1E6*(d-1E3*e)|0;return 0}function h$_hs_text_memcpy(b,c,d,e,f){return h$memcpy(b,2*c,d,2*e,2*f)}function h$_hs_text_memcmp(b,c,d,e,f){return h$memcmp(b,2*c,d,2*e,2*f)}
var h$_text_utf8d=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,8,8,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,10,3,3,3,3,3,3,3,3,3,3,3,3,4,3,3,11,
6,6,6,5,8,8,8,8,8,8,8,8,8,8,8,0,12,24,36,60,96,84,12,12,12,48,72,12,12,12,12,12,12,12,12,12,12,12,12,12,0,12,12,12,12,12,0,12,0,12,12,12,24,12,12,12,12,12,24,12,24,12,12,12,12,12,12,12,12,12,24,12,12,12,12,12,24,12,12,12,12,12,12,12,24,12,12,12,12,12,12,12,12,12,36,12,36,12,12,12,36,12,12,12,12,12,36,12,36,12,12,12,36,12,12,12,12,12,12,12,12,12,12];
function h$_hs_text_decode_utf8_internal(b,c,d,e,f,g,h,k){if(null===e||null===g)return h$ret1=h,null;g=c.dv.getUint32(d,!0)<<1;var l=k.state,m=k.codepoint;b=b.dv;for(var p=e.dv;f<h;){var n=p.getUint8(f++),q=h$_text_utf8d[n];m=0!==l?n&63|m<<6:255>>>q&n;l=h$_text_utf8d[256+l+q];if(0!==l)if(12!==l)continue;else break;65535>=m?(b.setUint16(g,m,!0),g+=2):(b.setUint16(g,55232+(m>>>10),!0),b.setUint16(g+2,56320+(m&1023),!0),g+=4);k.last=f}k.state=l;k.codepoint=m;c.dv.setUint32(d,g>>1,!0);h$ret1=f;return e}
function h$_hs_text_decode_utf8_state(b,c,d,e,f,g,h,k,l,m,p){var n={state:m.dv.getUint32(p,!0),codepoint:k.dv.getUint32(l,!0),last:f};b=h$_hs_text_decode_utf8_internal(b,c,d,e.arr[f][0],e.arr[f][1],g,h,n);c=h$ret1;e.arr[f][1]=n.last;m.dv.setUint32(p,n.state,!0);k.dv.setUint32(l,n.codepoint,!0);12===n.state&&c--;h$ret1=c;return b}
function h$_hs_text_decode_utf8(b,c,d,e,f,g,h){var k={state:0,codepoint:0,last:f};b=h$_hs_text_decode_utf8_internal(b,c,d,e,f,g,h,k);c=h$ret1;0!==k.state&&c--;h$ret1=c;return b}function h$_hs_text_decode_latin1(b,c,d,e,f){e=0;var g=c.u8;c=c.u3;for(b=b.u1;d!=f&&d&3;)b[e++]=g[d++];if(c)for(;d<f-3;){var h=c[d>>2];b[e++]=h&255;b[e++]=h>>>8&255;b[e++]=h>>>16&255;b[e++]=h>>>32&255;d+=4}for(;d!=f;)b[e++]=g[d++]}
function h$_hs_text_encode_utf8(b,c,d,e,f){var g=b.arr[c][0],h=b.arr[c][1];f=e+f;var k=d.u1;if(!k)throw"h$_hs_text_encode_utf8: invalid alignment for source";d=d.u3;for(g=g.u8;e<f;){for(;d&&!(e&1)&&2<=f-e;){var l=d[e>>1];if(l&4286644096)break;g[h++]=l&65535;g[h++]=l>>>16;e+=2}for(;e<f;)if(l=k[e++],127>=l){g[h++]=l;break}else 2047>=l?(g[h++]=l>>6|192,g[h++]=l&63|128):55296>l||56319<l?(g[h++]=l>>>12|224,g[h++]=l>>6&63|128,g[h++]=l&63|128):(l=(l-55296<<10)+(k[e++]-56320)+65536,g[h++]=l>>>18|240,g[h++]=
l>>12&63|128,g[h++]=l>>6&63|128,g[h++]=l&63|128)}b.arr[c][1]=h}
function h$process_pipeFd(b,c){var d=h$base_fdN--,e={};h$base_fds[d]=e;c?(e.err=null,e.waiting=new h$Queue,e.close=function(c,d,e){delete h$base_fds[c];b.end();e(0)},b.on("error",function(b){e.err=b}),e.write=function(c,d,e,k,l,m){d.err&&(h$setErrno(d.err),m(-1));c=e.u8;d=new Buffer(l);for(e=0;e<l;e++)d[e]=c[k+e];b.write(d,function(){m(l)})}):(e.close=function(b,c,d){delete h$base_fds[b];d(0)},e.waiting=new h$Queue,e.chunk={buf:null,pos:0,processing:!1},e.eof=!1,e.err=null,b.on("data",function(c){e.chunk.buf=
e.chunk.buf?Buffer.concat([e.chunk.buf,c]):c;h$process_process_pipe(e,b)}),b.pause(),b.on("readable",function(){h$process_process_pipe(e,b)}),b.on("end",function(){e.eof=!0;h$process_process_pipe(e,b)}),b.on("error",function(c){e.err=c;h$process_process_pipe(e,b)}),e.read=function(c,d,e,k,l,m){d.waiting.enqueue({buf:e,off:k,n:l,c:m});h$process_process_pipe(d,b)});return d}
function h$process_process_pipe(b,c){var d=b.chunk,e=b.waiting;if(e.length()&&!d.processing){for(d.processing=!0;b.err&&e.length();)h$setErrno(b.err),e.dequeue().c(-1);d.buf||(d.pos=0,d.buf=c.read());for(;d.buf&&e.length();){for(var f=e.dequeue(),g=Math.min(d.buf.length-d.pos,f.n),h=0;h<g;h++)f.buf.u8[h+f.off]=d.buf[d.pos+h];d.pos+=g;f.c(g);d.pos>=d.buf.length&&(d.buf=null);!d.buf&&e.length()&&(d.pos=0,d.buf=c.read())}for(;b.eof&&e.length();)e.dequeue().c(0);d.processing=!1}}
function h$process_runInteractiveProcess(b,c,d,e,f,g,h,k,l,m){if(h$isNode){if(-1===f)k="pipe";else if(0===f)k=process.stdin;else throw"runInteractiveProcess: custom stdin unsupported";if(-1===g)m="pipe";else if(1===g)m=process.stdout;else throw"runInteractiveProcess: custom stdout unsupported";if(-1===h)var p="pipe";else if(2===h)p=process.stderr;else throw"runInteractiveProcess: custom stderr unsupported";l={detached:l,stdio:[k,m,p]};null!==d&&(l.cwd=d);if(null!==e){d={};for(k=0;k<e.length;k+=2)d[e[k]]=
e[k+1];process.env.GHCJS_BOOTING&&(d.GHCJS_BOOTING=1);process.env.GHCJS_BOOTING1&&(d.GHCJS_BOOTING1=1);l.env=d}try{var n=h$child.spawn(b,c,l)}catch(r){if(-1!==r.toString().indexOf("EBADF")&&l.stdio[0]===process.stdin)l.stdio[0]="ignore",n=h$child.spawn(b,c,l);else throw r;}n.on("exit",function(b,c){q.exit=b;for(c=0;c<q.waiters.length;c++)q.waiters[c](b)});var q={pid:h$nProc,fds:[-1===f?h$process_pipeFd(n.stdio[0],!0):0,-1===g?h$process_pipeFd(n.stdio[1],!1):1,-1===h?h$process_pipeFd(n.stdio[2],!1):
2],exit:null,waiters:[],child:n};return h$procs[h$nProc++]=q}throw"$process_runInteractiveProcess: unsupported";}var h$nProc=1,h$procs=[];
function h$process_commandToProcess(b,c){if(h$isNode){if("win32"===process.platform){if(null===c){var d=process.env.COMSPEC;if(!d)if(d=h$directory_findExecutables("cmd.exe"),d.length)d=b[0];else{d=h$directory_findExecutables("command.com");if(!d.length)return null;d=d[0]}return[d,d+" /c "+c]}b=[b];return b=b.concat(c)}if(null===c)return["/bin/sh","-c",b];b=[b];return b=b.concat(c)}throw"process_commandToProcess: unsupported";}
function h$process_terminateProcess(b){h$isNode&&h$procs[b].child.kill();return 0}function h$process_getProcessExitCode(b,c,d){b=h$procs[b];if(null===b.exit)return 0;c.i3[d]=b.exit;return 1}function h$process_waitForProcess(b,c,d,e){if(h$isNode){var f=h$procs[b];null!==f.exit?(h$process_getProcessExitCode(b,c,d),e(0)):f.waiters.push(function(b){c.i3[d]=b;e(0)})}else h$unsupported(-1,e)}function h$hashable_fnv_hash_offset(b,c,d,e){return h$hashable_fnv_hash(b,c,d,e)}
function h$hashable_fnv_hash(b,c,d,e){if(0<d){b=b.u8;for(var f=0;f<d;f++)e=h$mulInt32(e,16777619)^b[c+f]}return e}function h$hashable_getRandomBytes(b,c,d){if(0<d){b=b.u8;for(var e=0;e<d;e++)b[c+e]=Math.floor(256*Math.random())}return d}function h$isFloat(b){return b===+b&&b!==(b|0)}function h$isInteger(b){return b===+b&&b===(b|0)}
function h$typeOf(b){return b instanceof Object?"[object Array]"==Object.prototype.toString.call(b)?5:b?6:0:null==b?0:"number"==typeof b?h$isInteger(b)?1:2:"boolean"==typeof b?3:4}function h$flattenObj(b){var c=[],d=0,e;for(e in b)c[d++]=[e,b[e]];return c}function h$buildObject(){for(var b={},c=arguments.length,d=0;d<c;d+=2)b[arguments[d]]=arguments[d+1];return b}
function h$buildObjectFromList(b){for(var c={},d,e,f;b.f===h$ghczmprimZCGHCziTypesziZC_con_e;)if(b=b.d2,f=b.d2,f.f===h$ghczmprimZCGHCziTypesziZC_con_e)d=b.d1,e=f.d1,b=f.d2,c[d]=e;else break;return c}function h$buildObjectFromTupList(b){for(var c={};b.f===h$ghczmprimZCGHCziTypesziZC_con_e;){var d=b.d1;b=b.d2;c[d.d1.d1]=d.d2.d1}return c}function h$filepath_isWindows(){return h$isNode&&"win32"===process.platform?!0:!1}
function h$directory_getPermissions(b,c){h$isNode?h$fs.stat(b,function(b,e){if(b)h$handleErrnoC(b,-1,0,c);else{b=e.mode;var d=e=b&1||b&8||b&64;"win32"==process.platform&&(d=!0);c((b&4||b&32||b&256?1:0)|(b&2||b&16||b&128?2:0)|(d?4:0)|(e?8:0))}}):h$unsupported(-1,c)}function h$directory_setPermissions(b,c,d){h$isNode?h$fs.stat(b,function(c,f){c?h$handleErrnoC(c,-1,0,d):h$fs.chmod(b,function(b){h$handleErrnoC(b,-1,0,d)})}):h$unsupported(-1,d)}
function h$directory_copyPermissions(b,c,d){h$isNode?h$fs.stat(b,function(b,f){b?h$handleErrnoC(b,-1,0,d):h$fs.chmod(c,f.mode,function(b){h$handleErrnoC(b,-1,0,d)})}):h$unsupported(-1,d)}function h$directory_createDirectory(b,c){h$isNode?h$fs.mkdir(b,function(b){h$handleErrnoC(b,-1,0,c)}):h$unsupported(-1,c)}function h$directory_removeDirectory(b,c){h$isNode?h$fs.rmdir(b,function(b){h$handleErrnoC(b,-1,0,c)}):h$unsupported(-1,c)}
function h$directory_removeFile(b,c){h$isNode?h$fs.unlink(b,function(b){h$handleErrnoC(b,-1,0,c)}):h$unsupported(-1,c)}function h$directory_renameDirectory(b,c,d){h$isNode?h$fs.rename(b,c,function(b){h$handleErrnoC(b,-1,0,d)}):h$unsupported(-1,d)}function h$directory_renameFile(b,c,d){h$isNode?h$fs.rename(b,c,function(b){h$handleErrnoC(b,-1,0,d)}):h$unsupported(-1,d)}function h$directory_canonicalizePath(b){return h$isNode?h$path.normalize(b):b}
function h$directory_findExecutables(b,c){if(h$isNode){var d=[],e=process.env.PATH.split("win32"===process.platform?";":":"),f=[];f.push(null);files=[];d=[];for(var g=0;g<e.length;g++)for(var h=0;h<f.length;h++)files.push(e[g]+h$path.sep+b+(f[h]?f[h]:""));var k=function(b){b>=files.length?c(d):h$fs.stat(files[b],function(c,e){!c&&(e.mode&73||"win32"===process.platform)&&d.push(files[b]);k(b+1)})};k(0)}else c([])}
function h$directory_getDirectoryContents(b,c){h$isNode?h$fs.readdir(b,function(b,e){h$handleErrnoC(b,null,e,c)}):h$unsupported(null,c)}function h$directory_getCurrentDirectory(){return h$isNode?h$handleErrno(null,function(){return process.cwd()}):"/"}function h$directory_setCurrentDirectory(b){return h$isNode?h$handleErrnoS(-1,0,function(){return process.chdir(b)}):h$unsupported(-1)}
function h$directory_getHomeDirectory(b){return h$isNode?process.env.HOME||process.env.HOMEPATH||process.env.USERPROFILE:"/"}function h$directory_getAppUserDataDirectory(b){if(h$isNode){if(process.env.APPDATA)return process.env.APPDATA+h$path.sep+b;if(process.env.HOME)return process.env.HOME+h$path.sep+"."+b}return"/"}function h$directory_getUserDocumentsDirectory(b){return h$isNode&&process.env.HOME?process.env.HOME:"/"}
function h$directory_getTemporaryDirectory(){return h$isNode?h$handleErrno(null,function(){return h$os.tmpdir()}):"/"}function h$directory_exeExtension(){return h$isNode?"windows"===h$os.platform()?"exe":"":""}function h$directory_getFileStatus(b,c){h$isNode?h$fs.stat(b,function(b,e){h$handleErrnoC(b,null,e,c)}):h$unsupported(null,c)}function h$directory_getFileOrSymlinkStatus(b,c){h$isNode?h$fs.lstat(b,function(b,e){h$handleErrnoC(b,null,e,c)}):h$unsupported(null,c)}
function h$directory_getFileStatusAccessTime(b){return b.atime.getTime()}function h$directory_getFileStatusModificationTime(b){return b.mtime.getTime()}function h$directory_getFileStatusIsDirectory(b){return b.isDirectory()}function h$directory_getFileStatusIsSymbolicLink(b){return b.isSymbolicLink()}function h$chmod(b,c,d){return h$isNode?(b=h$decodeUtf8z(b,c),h$fs.chmodSync(b,d),0):h$unsupported(-1)}function h$fps_reverse(b,c,d,e,f){if(0<f){b=b.u8;d=d.u8;for(var g=0;g<f;g++)b[c+f-g-1]=d[e+g]}}
function h$fps_intersperse(b,c,d,e,f,g){if(0<f){b=b.u8;d=d.u8;for(var h=0;h<f-1;h++)b[c]=d[e+h],b[c+1]=g,c+=2;b[c]=d[e+f-1]}}function h$fps_maximum(b,c,d){if(0<d){b=b.u8;for(var e=b[c],f=1;f<d;f++){var g=b[c+f];g>e&&(e=g)}return e}return 0}function h$fps_minimum(b,c,d){if(0<d){var e=b.u8;b=b.u8[c];for(var f=1;f<d;f++){var g=e[c+f];g<b&&(b=g)}return b}return 255}function h$fps_count(b,c,d,e){if(0<d){b=b.u8;for(var f=0,g=0;g<d;g++)b[c+g]===e&&f++;return f|0}return 0}
function h$fps_memcpy_offsets(b,c,d,e,f,g,h){return memcpy(b,c+d,e,f+g,h)}var h$_hs_bytestring_digits=[48,49,50,51,52,53,54,55,56,57,97,98,99,100,101,102],h$_hs_bytestring_l10=goog.math.Long.fromBits(10,0);function h$_hs_bytestring_int_dec(b,c,d){var e=d,f=c.u8;if(0>b){f[e++]=45;d++;var g=b;b=b/10|0;f[e++]=h$_hs_bytestring_digits[10*b-g];if(0===b)return h$ret1=e,c;b=-b}do g=b,b=b/10|0,f[e++]=h$_hs_bytestring_digits[g-10*b];while(b);for(g=e--;d<e;)b=f[e],f[e--]=f[d],f[d++]=b;h$ret1=g;return c}
function h$_hs_bytestring_long_long_int_dec(b,c,d,e){var f=h$_hs_bytestring_l10,g=goog.math.Long.fromBits(c,b);b=e;c=d.u8;if(g.isNegative()){c[b++]=45;e++;x_tmp=g;g=g.div(f);c[b++]=h$_hs_bytestring_digits[g.multiply(f).subtract(x_tmp).getLowBits()];if(g.isZero())return h$ret1=b,d;g=g.negate()}do x_tmp=g,g=g.div(f),c[b++]=h$_hs_bytestring_digits[x_tmp.subtract(g.multiply(f))];while(!g.isZero());for(g=b--;e<b;)f=c[b],c[b--]=c[e],c[e++]=f;h$ret1=g;return d}
function h$_hs_bytestring_uint_dec(b,c,d){var e=d,f=c.u8;0>b&&(b+=4294967296);do{var g=b;b=b/10|0;f[e++]=h$_hs_bytestring_digits[g-10*b]}while(b);for(g=e--;d<e;)b=f[e],f[e--]=f[d],f[d++]=b;h$ret1=g;return c}
function h$_hs_bytestring_long_long_uint_dec(b,c,d,e){var f=e,g=d.u8;b=h$ghcjsbn_mkBigNat_ww(b,c);c=[];var h=[];do h$ghcjsbn_quotRem_bw(c,h,b,10),b=c,g[f++]=h$_hs_bytestring_digits[h$ghcjsbn_toInt_b(h)];while(!h$ghcjsbn_isZero_b(b));for(c=f--;e<f;)b=g[f],g[f--]=g[e],g[e++]=b;h$ret1=c;return d}function h$_hs_bytestring_int_dec_padded9(b,c,d){var e=d+9;c=c.u8;do{var f=b;b=b/10|0;c[--e]=h$_hs_bytestring_digits[f-10*b]}while(b);for(;d<e;)c[--e]=48}
function h$_hs_bytestring_long_long_int_dec_padded18(b,c,d,e){var f=h$_hs_bytestring_l10,g=e+18;d=d.u8;b=goog.math.Long.fromBits(c,b);do x_tmp=b,b=b.div(f),d[--g]=h$_hs_bytestring_digits[x_tmp.subtract(b.multiply(f))];while(!b.isZero());for(;e<g;)d[--g]=48}function h$_hs_bytestring_uint_hex(b,c,d){var e=d,f,g=c.u8;do g[e++]=h$_hs_bytestring_digits[b&15],b>>>=4;while(b);for(f=e--;d<e;)b=g[e],g[e--]=g[d],g[d++]=b;h$ret1=f;return c}
function h$_hs_bytestring_long_long_uint_hex(b,c,d,e){var f=e,g=d.u8;if(0===b&&0===c)g[f++]=48;else{for(;0!==c;)g[f++]=h$_hs_bytestring_digits[c&15],c>>>=4;for(;0!==b;)g[f++]=h$_hs_bytestring_digits[b&15],b>>>=4}for(c=f--;e<f;)b=g[f],g[f--]=g[e],g[e++]=b;h$ret1=c;return d};
