var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,b,c){a instanceof String&&(a=String(a));for(var d=a.length,e=0;e<d;e++){var f=a[e];if(b.call(c,f,e,a))return{i:e,v:f}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};
$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,c){return $jscomp.findInternal(this,a,c).v}},"es6","es3");$jscomp.checkStringArgs=function(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""};
$jscomp.polyfill("String.prototype.repeat",function(a){return a?a:function(a){var b=$jscomp.checkStringArgs(this,null,"repeat");if(0>a||1342177279<a)throw new RangeError("Invalid count value");a|=0;for(var d="";a;)if(a&1&&(d+=b),a>>>=1)b+=b;return d}},"es6","es3");void 0===Object.create&&(Object.create=function(a){function b(){}b.prototype=a;return new b});function Fay$$objConcat(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c]);return a}
function Fay$$_(a,b){for(;a instanceof Fay$$$;)a=a.force(b);return a}function Fay$$__(){for(var a=arguments[0],b=1,c=arguments.length;b<c;b++)a=(a instanceof Fay$$$?Fay$$_(a):a)(arguments[b]);return a}function Fay$$$(a){this.forced=!1;this.value=a}Fay$$$.prototype.force=function(a){return a?this.value():this.forced?this.value:(this.value=this.value(),this.forced=!0,this.value)};function Fay$$seq(a){return function(b){Fay$$_(a,!1);return b}}
function Fay$$seq$36$uncurried(a,b){Fay$$_(a,!1);return b}function Fay$$Monad(a){this.value=a}function Fay$$then(a){return function(b){return Fay$$bind(a)(function(a){return b})}}function Fay$$then$36$uncurried(a,b){return Fay$$bind$36$uncurried(a,function(a){return b})}function Fay$$bind(a){return function(b){return new Fay$$$(function(){var c=Fay$$_(a,!0);return Fay$$_(b)(c.value)})}}
function Fay$$bind$36$uncurried(a,b){return new Fay$$$(function(){var c=Fay$$_(a,!0);return Fay$$_(b)(c.value)})}function Fay$$$_return(a){return new Fay$$Monad(a)}function Fay$$force(a){return function(b){return new Fay$$$(function(){Fay$$_(a,b);return new Fay$$Monad(Fay$$unit)})}}function Fay$$return$36$uncurried(a){return new Fay$$Monad(a)}var Fay$$unit=null;
function Fay$$fayToJs(a,b){var c=a[0],d=a[1];if("action"==c)return function(){return Fay$$fayToJs(d[0],Fay$$_(b,!0).value)};if("function"==c)return function(){var a=b,c=d[d.length-1],h=d.length;if(1<h){a=Fay$$_(a,!0);if("automatic_function"==d){for(var g=0;g<arguments.length;g++)a=Fay$$_(a(Fay$$jsToFay(["automatic"],arguments[g])),!0);return Fay$$fayToJs(["automatic"],a)}for(g=0;g<h-1&&a instanceof Function;g++)a=Fay$$_(a(Fay$$jsToFay(d[g],arguments[g])),!0);h=c[1];return"action"==c[0]?Fay$$fayToJs(h[0],
a.value):Fay$$fayToJs(c,a)}throw Error("Nullary function?");};if("string"==c)return Fay$$fayToJs_string(b);if("list"==c){a=[];for(b=Fay$$_(b);b instanceof Fay$$Cons;)a.push(Fay$$fayToJs(d[0],b.car)),b=Fay$$_(b.cdr);return a}if("tuple"==c){a=[];b=Fay$$_(b);for(c=0;b instanceof Fay$$Cons;)a.push(Fay$$fayToJs(d[c++],b.car)),b=Fay$$_(b.cdr);return a}if("defined"==c)return b=Fay$$_(b),b instanceof Fay.FFI._Undefined?void 0:Fay$$fayToJs(d[0],b.slot1);if("nullable"==c)return b=Fay$$_(b),b instanceof Fay.FFI._Null?
null:Fay$$fayToJs(d[0],b.slot1);if("double"==c||"int"==c||"bool"==c)return Fay$$_(b);if("ptr"==c)return b;if("unknown"==c)return Fay$$fayToJs(["automatic"],b);if("automatic"==c&&b instanceof Function)return Fay$$fayToJs(["function","automatic_function"],b);if("automatic"==c||"user"==c){b=Fay$$_(b);if(b instanceof Fay$$Cons||null===b){for(a=[];b instanceof Fay$$Cons;)a.push(Fay$$fayToJs(["automatic"],b.car)),b=Fay$$_(b.cdr);return a}return(c=b&&b.instance&&Fay$$fayToJsHash[b.instance])?c(a,a[2],b):
b}throw Error("Unhandled Fay->JS translation type: "+c);}var Fay$$fayToJsHash={};function Fay$$fayToJs_string(a){var b="";for(a=Fay$$_(a);a instanceof Fay$$Cons;)b+=Fay$$_(a.car),a=Fay$$_(a.cdr);return b}function Fay$$jsToFay_string(a){return Fay$$list(a)}function Fay$$jsToFay_int(a){return a}function Fay$$jsToFay_double(a){return a}function Fay$$jsToFay_bool(a){return a}function Fay$$fayToJs_int(a){return Fay$$_(a)}function Fay$$fayToJs_double(a){return Fay$$_(a)}
function Fay$$fayToJs_bool(a){return Fay$$_(a)}
function Fay$$jsToFay(a,b){var c=a[0],d=a[1];if("action"==c)return new Fay$$Monad(Fay$$jsToFay(d[0],b));if("function"==c){var e=d[d.length-1],f=d.slice(0,-1);if(0<b.length){var h=function(a){return function(c){c=Fay$$fayToJs(f[a.length],c);var d=a.concat([c]);return d.length==f.length?new Fay$$$(function(){return Fay$$jsToFay(e,b.apply(this,d))}):h(d)}};return h([])}return function(a){return Fay$$jsToFay(["automatic"],b(Fay$$fayToJs(["automatic"],a)))}}if("string"==c)return Fay$$list(b);if("list"==
c){c=[];var g=0;for(a=b.length;g<a;g++)c.push(Fay$$jsToFay(d[0],b[g]));return Fay$$list(c)}if("tuple"==c){c=[];g=0;for(a=b.length;g<a;g++)c.push(Fay$$jsToFay(d[g],b[g]));return Fay$$list(c)}if("defined"==c)return void 0===b?new Fay.FFI._Undefined:new Fay.FFI._Defined(Fay$$jsToFay(d[0],b));if("nullable"==c)return null===b?new Fay.FFI._Null:new Fay.FFI.Nullable(Fay$$jsToFay(d[0],b));if("int"==c){g=Math.round(b);if(g!==b)throw"Argument "+b+" is not an integer!";return g}if("double"==c||"bool"==c||"ptr"==
c)return b;if("unknown"==c)return Fay$$jsToFay(["automatic"],b);if("automatic"==c&&b instanceof Function){a=[["automatic"]];for(g=0;g<b.length;g++)a.push(["automatic"]);return Fay$$jsToFay(["function",a],b)}if("automatic"==c&&b instanceof Array){d=null;for(g=b.length-1;0<=g;g--)d=new Fay$$Cons(Fay$$jsToFay([c],b[g]),d);return d}if("automatic"==c||"user"==c)return b&&b.instance?(g=Fay$$jsToFayHash[b.instance])?g(a,a[2],b):b:b;throw Error("Unhandled JS->Fay translation type: "+c);}
var Fay$$jsToFayHash={};function Fay$$Cons(a,b){this.car=a;this.cdr=b}function Fay$$list(a){for(var b=null,c=a.length-1;0<=c;c--)b=new Fay$$Cons(a[c],b);return b}function Fay$$cons(a){return function(b){return new Fay$$Cons(a,b)}}function Fay$$index(a,b){for(var c=0;c<a;c++)b=Fay$$_(b.cdr);return b.car}function Fay$$listLen(a,b){for(var c=0;null!==a&&c<b+1;c++)a=Fay$$_(a.cdr);return c==b}function Fay$$mult(a){return function(b){return new Fay$$$(function(){return Fay$$_(a)*Fay$$_(b)})}}
function Fay$$mult$36$uncurried(a,b){return new Fay$$$(function(){return Fay$$_(a)*Fay$$_(b)})}function Fay$$add(a){return function(b){return new Fay$$$(function(){return Fay$$_(a)+Fay$$_(b)})}}function Fay$$add$36$uncurried(a,b){return new Fay$$$(function(){return Fay$$_(a)+Fay$$_(b)})}function Fay$$sub(a){return function(b){return new Fay$$$(function(){return Fay$$_(a)-Fay$$_(b)})}}function Fay$$sub$36$uncurried(a,b){return new Fay$$$(function(){return Fay$$_(a)-Fay$$_(b)})}
function Fay$$divi(a){return function(b){return new Fay$$$(function(){return Fay$$_(a)/Fay$$_(b)})}}function Fay$$divi$36$uncurried(a,b){return new Fay$$$(function(){return Fay$$_(a)/Fay$$_(b)})}
function Fay$$equal(a,b){a=Fay$$_(a);b=Fay$$_(b);if(a===b)return!0;if(a instanceof Array){if(a.length!=b.length)return!1;for(var c=a.length,d=0;d<c;d++)if(!Fay$$equal(a[d],b[d]))return!1;return!0}if(a instanceof Fay$$Cons&&b instanceof Fay$$Cons){do{if(!Fay$$equal(a.car,b.car))return!1;a=Fay$$_(a.cdr);b=Fay$$_(b.cdr);if(null===a||null===b)return a===b}while(1)}else{if("object"==typeof a&&"object"==typeof b&&a&&b&&a.instance===b.instance){for(c in a)if(!Fay$$equal(a[c],b[c]))return!1;return!0}return!1}}
function Fay$$eq(a){return function(b){return new Fay$$$(function(){return Fay$$equal(a,b)})}}function Fay$$eq$36$uncurried(a,b){return new Fay$$$(function(){return Fay$$equal(a,b)})}function Fay$$neq(a){return function(b){return new Fay$$$(function(){return!Fay$$equal(a,b)})}}function Fay$$neq$36$uncurried(a,b){return new Fay$$$(function(){return!Fay$$equal(a,b)})}function Fay$$gt(a){return function(b){return new Fay$$$(function(){return Fay$$_(a)>Fay$$_(b)})}}
function Fay$$gt$36$uncurried(a,b){return new Fay$$$(function(){return Fay$$_(a)>Fay$$_(b)})}function Fay$$lt(a){return function(b){return new Fay$$$(function(){return Fay$$_(a)<Fay$$_(b)})}}function Fay$$lt$36$uncurried(a,b){return new Fay$$$(function(){return Fay$$_(a)<Fay$$_(b)})}function Fay$$gte(a){return function(b){return new Fay$$$(function(){return Fay$$_(a)>=Fay$$_(b)})}}function Fay$$gte$36$uncurried(a,b){return new Fay$$$(function(){return Fay$$_(a)>=Fay$$_(b)})}
function Fay$$lte(a){return function(b){return new Fay$$$(function(){return Fay$$_(a)<=Fay$$_(b)})}}function Fay$$lte$36$uncurried(a,b){return new Fay$$$(function(){return Fay$$_(a)<=Fay$$_(b)})}function Fay$$and(a){return function(b){return new Fay$$$(function(){return Fay$$_(a)&&Fay$$_(b)})}}function Fay$$and$36$uncurried(a,b){return new Fay$$$(function(){return Fay$$_(a)&&Fay$$_(b)})}function Fay$$or(a){return function(b){return new Fay$$$(function(){return Fay$$_(a)||Fay$$_(b)})}}
function Fay$$or$36$uncurried(a,b){return new Fay$$$(function(){return Fay$$_(a)||Fay$$_(b)})}function Fay$$Ref(a){this.value=a}function Fay$$writeRef(a,b){a.value=b}function Fay$$readRef(a){return a.value}function Fay$$date(a){return Date.parse(a)}function Fay$$Ref2(a){this.val=a}function Fay$$Sig(){this.handlers=[]}function Fay$$Var(a){this.val=a;this.handlers=[]}
function Fay$$broadcastInternal(a,b,c){for(var d=a.handlers,e=[],f=d.length,h=0;h<f;h++)try{c(d[h][1](b),!0)}catch(g){e.push(g)}if(0<e.length)for(console.error("Encountered "+e.length+" exception(s) while broadcasing a change to ",a),f=e.length,h=0;h<f;h++)(function(a){setTimeout(function(){throw a;},0)})(e[h])}
function Fay$$setValue(a,b,c){if(a instanceof Fay$$Ref2)a.val=b;else if(a instanceof Fay$$Var)a.val=b,Fay$$broadcastInternal(a,b,c);else if(a instanceof Fay$$Sig)Fay$$broadcastInternal(a,b,c);else throw"Fay$$setValue given something that's not a Ref2, Var, or Sig";}
function Fay$$subscribe(a,b){var c={};a.handlers.push([c,b]);var d=a.handlers.length-1;return function(b){for(var e=Math.min(d,a.handlers.length-1);0<=e;e--)if(a.handlers[e][0]==c){a.handlers=a.handlers.slice(0,e).concat(a.handlers.slice(e+1));return}return b}}var Data={Data:{}},Fay={FFI:{}};Fay.FFI._Nullable=function(a){this.slot1=a};Fay.FFI._Nullable.prototype.instance="Nullable";Fay.FFI.Nullable=function(a){return new Fay$$$(function(){return new Fay.FFI._Nullable(a)})};Fay.FFI._Null=function(){};
Fay.FFI._Null.prototype.instance="Null";Fay.FFI.Null=new Fay$$$(function(){return new Fay.FFI._Null});Fay.FFI._Defined=function(a){this.slot1=a};Fay.FFI._Defined.prototype.instance="Defined";Fay.FFI.Defined=function(a){return new Fay$$$(function(){return new Fay.FFI._Defined(a)})};Fay.FFI._Undefined=function(){};Fay.FFI._Undefined.prototype.instance="Undefined";Fay.FFI.Undefined=new Fay$$$(function(){return new Fay.FFI._Undefined});
Fay$$objConcat(Fay$$fayToJsHash,{Nullable:function(a,b,c){var d={instance:"Nullable"};a=Fay$$fayToJs(b&&b[0]?b[0]:"automatic"===a[0]?["automatic"]:["unknown"],c.slot1);void 0!==a&&(d.slot1=a);return d},Null:function(a,b,c){return{instance:"Null"}},Defined:function(a,b,c){var d={instance:"Defined"};a=Fay$$fayToJs(b&&b[0]?b[0]:"automatic"===a[0]?["automatic"]:["unknown"],c.slot1);void 0!==a&&(d.slot1=a);return d},Undefined:function(a,b,c){return{instance:"Undefined"}}});
Fay$$objConcat(Fay$$jsToFayHash,{Nullable:function(a,b,c){return new Fay.FFI._Nullable(Fay$$jsToFay(b&&b[0]?b[0]:"automatic"===a[0]?["automatic"]:["unknown"],c.slot1))},Null:function(a,b,c){return new Fay.FFI._Null},Defined:function(a,b,c){return new Fay.FFI._Defined(Fay$$jsToFay(b&&b[0]?b[0]:"automatic"===a[0]?["automatic"]:["unknown"],c.slot1))},Undefined:function(a,b,c){return new Fay.FFI._Undefined}});var Prelude={_Just:function(a){this.slot1=a}};Prelude._Just.prototype.instance="Just";
Prelude.Just=function(a){return new Fay$$$(function(){return new Prelude._Just(a)})};Prelude._Nothing=function(){};Prelude._Nothing.prototype.instance="Nothing";Prelude.Nothing=new Fay$$$(function(){return new Prelude._Nothing});Prelude._Left=function(a){this.slot1=a};Prelude._Left.prototype.instance="Left";Prelude.Left=function(a){return new Fay$$$(function(){return new Prelude._Left(a)})};Prelude._Right=function(a){this.slot1=a};Prelude._Right.prototype.instance="Right";Prelude.Right=function(a){return new Fay$$$(function(){return new Prelude._Right(a)})};
Prelude.maybe=function(a){return function(b){return function(c){return new Fay$$$(function(){if(Fay$$_(c)instanceof Prelude._Nothing)return a;if(Fay$$_(c)instanceof Prelude._Just){var d=Fay$$_(c).slot1;return Fay$$_(b)(d)}throw["unhandled case in maybe",[a,b,c]];})}}};Prelude.$62$$62$$61$=function(a){return function(b){return new Fay$$$(function(){return Fay$$_(Fay$$bind(a)(b))})}};Prelude.$62$$62$=function(a){return function(b){return new Fay$$$(function(){return Fay$$_(Fay$$then(a)(b))})}};
Prelude.$_return=function(a){return new Fay$$$(function(){return new Fay$$Monad(Fay$$jsToFay(["unknown"],Fay$$$_return(Fay$$fayToJs(["unknown"],a))))})};Prelude.fail=new Fay$$$(function(){return Prelude.error});Prelude.when=function(a){return function(b){return new Fay$$$(function(){return Fay$$_(a)?b:Fay$$_(Fay$$$_return)(Fay$$unit)})}};Prelude.unless=function(a){return function(b){return new Fay$$$(function(){return Fay$$_(a)?Fay$$_(Fay$$$_return)(Fay$$unit):b})}};Prelude.forM=function(a){return function(b){return new Fay$$$(function(){return Fay$$_(Fay$$_(Prelude.$36$)(Prelude.sequence))(Fay$$_(Fay$$_(Prelude.map)(b))(a))})}};
Prelude.forM_=function(a){return function(b){return new Fay$$$(function(){var c=Fay$$_(a);if(c instanceof Fay$$Cons){var d=c.car;c=c.cdr;return Fay$$_(Fay$$_(Fay$$then)(Fay$$_(b)(d)))(Fay$$_(Fay$$_(Prelude.forM_)(c))(b))}if(null===Fay$$_(a))return Fay$$_(Fay$$$_return)(Fay$$unit);throw["unhandled case in forM_",[a,b]];})}};Prelude.mapM=function(a){return function(b){return new Fay$$$(function(){return Fay$$_(Fay$$_(Prelude.$36$)(Prelude.sequence))(Fay$$_(Fay$$_(Prelude.map)(a))(b))})}};
Prelude.mapM_=function(a){return function(b){return new Fay$$$(function(){var c=Fay$$_(b);if(c instanceof Fay$$Cons){var d=c.car;c=c.cdr;return Fay$$_(Fay$$_(Fay$$then)(Fay$$_(a)(d)))(Fay$$_(Fay$$_(Prelude.mapM_)(a))(c))}if(null===Fay$$_(b))return Fay$$_(Fay$$$_return)(Fay$$unit);throw["unhandled case in mapM_",[a,b]];})}};Prelude.$61$$60$$60$=function(a){return function(b){return new Fay$$$(function(){return Fay$$_(Fay$$_(Fay$$bind)(b))(a)})}};Prelude.$_void=function(a){return new Fay$$$(function(){return Fay$$_(Fay$$_(Fay$$then)(a))(Fay$$_(Fay$$$_return)(Fay$$unit))})};
Prelude.$62$$61$$62$=function(a){return function(b){return function(c){return new Fay$$$(function(){return Fay$$_(Fay$$_(Fay$$bind)(Fay$$_(a)(c)))(b)})}}};Prelude.$60$$61$$60$=function(a){return function(b){return function(c){return new Fay$$$(function(){return Fay$$_(Fay$$_(Fay$$bind)(Fay$$_(b)(c)))(a)})}}};Prelude.sequence=function(a){return new Fay$$$(function(){return function(){return Fay$$_(Fay$$_(Fay$$_(Prelude.foldr)(function(a){return function(b){return new Fay$$$(function(){return Fay$$_(Fay$$_(Fay$$bind)(a))(function(a){return Fay$$_(Fay$$_(Fay$$bind)(b))(function(b){return Fay$$_(Fay$$$_return)(Fay$$_(Fay$$_(Fay$$cons)(a))(b))})})})}}))(Fay$$_(Fay$$$_return)(null)))(a)}()})};
Prelude.sequence_=function(a){return new Fay$$$(function(){if(null===Fay$$_(a))return Fay$$_(Fay$$$_return)(Fay$$unit);var b=Fay$$_(a);if(b instanceof Fay$$Cons){var c=b.car;b=b.cdr;return Fay$$_(Fay$$_(Fay$$then)(c))(Fay$$_(Prelude.sequence_)(b))}throw["unhandled case in sequence_",[a]];})};Prelude._GT=function(){};Prelude._GT.prototype.instance="GT";Prelude.GT=new Fay$$$(function(){return new Prelude._GT});Prelude._LT=function(){};Prelude._LT.prototype.instance="LT";Prelude.LT=new Fay$$$(function(){return new Prelude._LT});
Prelude._EQ=function(){};Prelude._EQ.prototype.instance="EQ";Prelude.EQ=new Fay$$$(function(){return new Prelude._EQ});Prelude.compare=function(a){return function(b){return new Fay$$$(function(){return Fay$$_(Fay$$_(Fay$$_(Fay$$gt)(a))(b))?Prelude.GT:Fay$$_(Fay$$_(Fay$$_(Fay$$lt)(a))(b))?Prelude.LT:Prelude.EQ})}};Prelude.succ=function(a){return new Fay$$$(function(){return Fay$$_(Fay$$_(Fay$$add)(a))(1)})};Prelude.pred=function(a){return new Fay$$$(function(){return Fay$$_(Fay$$_(Fay$$sub)(a))(1)})};
Prelude.enumFrom=function(a){return new Fay$$$(function(){return Fay$$_(Fay$$_(Fay$$cons)(a))(Fay$$_(Prelude.enumFrom)(Fay$$_(Fay$$_(Fay$$add)(a))(1)))})};Prelude.enumFromTo=function(a){return function(b){return new Fay$$$(function(){return Fay$$_(Fay$$_(Fay$$_(Fay$$gt)(a))(b))?null:Fay$$_(Fay$$_(Fay$$cons)(a))(Fay$$_(Fay$$_(Prelude.enumFromTo)(Fay$$_(Fay$$_(Fay$$add)(a))(1)))(b))})}};Prelude.enumFromBy=function(a){return function(b){return new Fay$$$(function(){return Fay$$_(Fay$$_(Fay$$cons)(a))(Fay$$_(Fay$$_(Prelude.enumFromBy)(Fay$$_(Fay$$_(Fay$$add)(a))(b)))(b))})}};
Prelude.enumFromThen=function(a){return function(b){return new Fay$$$(function(){return Fay$$_(Fay$$_(Prelude.enumFromBy)(a))(Fay$$_(Fay$$_(Fay$$sub)(b))(a))})}};
Prelude.enumFromByTo=function(a){return function(b){return function(c){return new Fay$$$(function(){return function(){var d=function(a){return new Fay$$$(function(){return Fay$$_(Fay$$_(Fay$$_(Fay$$lt)(a))(c))?null:Fay$$_(Fay$$_(Fay$$cons)(a))(Fay$$_(d)(Fay$$_(Fay$$_(Fay$$add)(a))(b)))})},e=function(a){return new Fay$$$(function(){return Fay$$_(Fay$$_(Fay$$_(Fay$$gt)(a))(c))?null:Fay$$_(Fay$$_(Fay$$cons)(a))(Fay$$_(e)(Fay$$_(Fay$$_(Fay$$add)(a))(b)))})};return Fay$$_(Fay$$_(Fay$$_(Fay$$lt)(b))(0))?
Fay$$_(d)(a):Fay$$_(e)(a)}()})}}};Prelude.enumFromThenTo=function(a){return function(b){return function(c){return new Fay$$$(function(){return Fay$$_(Fay$$_(Fay$$_(Prelude.enumFromByTo)(a))(Fay$$_(Fay$$_(Fay$$sub)(b))(a)))(c)})}}};Prelude.fromIntegral=function(a){return new Fay$$$(function(){return a})};Prelude.fromInteger=function(a){return new Fay$$$(function(){return a})};Prelude.not=function(a){return new Fay$$$(function(){return Fay$$_(a)?!1:!0})};Prelude.otherwise=!0;
Prelude.show=function(a){return new Fay$$$(function(){return Fay$$jsToFay_string(JSON.stringify(Fay$$fayToJs(["automatic"],a)))})};Prelude.error=function(a){return new Fay$$$(function(){throw Fay$$fayToJs_string(a);})};Prelude.$_undefined=new Fay$$$(function(){return Fay$$_(Prelude.error)(Fay$$list("Prelude.undefined"))});
Prelude.either=function(a){return function(b){return function(c){return new Fay$$$(function(){if(Fay$$_(c)instanceof Prelude._Left){var d=Fay$$_(c).slot1;return Fay$$_(a)(d)}if(Fay$$_(c)instanceof Prelude._Right)return d=Fay$$_(c).slot1,Fay$$_(b)(d);throw["unhandled case in either",[a,b,c]];})}}};Prelude.until=function(a){return function(b){return function(c){return new Fay$$$(function(){return Fay$$_(Fay$$_(a)(c))?c:Fay$$_(Fay$$_(Fay$$_(Prelude.until)(a))(b))(Fay$$_(b)(c))})}}};
Prelude.$36$$33$=function(a){return function(b){return new Fay$$$(function(){return Fay$$_(Fay$$_(Fay$$seq)(b))(Fay$$_(a)(b))})}};Prelude.$_const=function(a){return function(b){return new Fay$$$(function(){return a})}};Prelude.id=function(a){return new Fay$$$(function(){return a})};Prelude.$46$=function(a){return function(b){return function(c){return new Fay$$$(function(){return Fay$$_(a)(Fay$$_(b)(c))})}}};Prelude.$36$=function(a){return function(b){return new Fay$$$(function(){return Fay$$_(a)(b)})}};
Prelude.flip=function(a){return function(b){return function(c){return new Fay$$$(function(){return Fay$$_(Fay$$_(a)(c))(b)})}}};Prelude.curry=function(a){return function(b){return function(c){return new Fay$$$(function(){return Fay$$_(a)(Fay$$list([b,c]))})}}};Prelude.uncurry=function(a){return function(b){return new Fay$$$(function(){if(Fay$$listLen(Fay$$_(b),2)){var c=Fay$$index(0,Fay$$_(b));var d=Fay$$index(1,Fay$$_(b));c=Fay$$_(Fay$$_(a)(c))(d)}else throw["unhandled case",b];return c})}};
Prelude.snd=function(a){return new Fay$$$(function(){if(Fay$$listLen(Fay$$_(a),2))return Fay$$index(1,Fay$$_(a));throw["unhandled case in snd",[a]];})};Prelude.fst=function(a){return new Fay$$$(function(){if(Fay$$listLen(Fay$$_(a),2))return Fay$$index(0,Fay$$_(a));throw["unhandled case in fst",[a]];})};
Prelude.div=function(a){return function(b){return new Fay$$$(function(){var c=b,d=a;if(Fay$$_(Fay$$_(Fay$$_(Fay$$and)(Fay$$_(Fay$$_(Fay$$gt)(d))(0)))(Fay$$_(Fay$$_(Fay$$lt)(c))(0))))return Fay$$_(Fay$$_(Fay$$sub)(Fay$$_(Fay$$_(Prelude.quot)(Fay$$_(Fay$$_(Fay$$sub)(d))(1)))(c)))(1);if(Fay$$_(Fay$$_(Fay$$_(Fay$$and)(Fay$$_(Fay$$_(Fay$$lt)(d))(0)))(Fay$$_(Fay$$_(Fay$$gt)(c))(0))))return Fay$$_(Fay$$_(Fay$$sub)(Fay$$_(Fay$$_(Prelude.quot)(Fay$$_(Fay$$_(Fay$$add)(d))(1)))(c)))(1);c=b;d=a;return Fay$$_(Fay$$_(Prelude.quot)(d))(c)})}};
Prelude.mod=function(a){return function(b){return new Fay$$$(function(){var c=b,d=a;if(Fay$$_(Fay$$_(Fay$$_(Fay$$and)(Fay$$_(Fay$$_(Fay$$gt)(d))(0)))(Fay$$_(Fay$$_(Fay$$lt)(c))(0))))return Fay$$_(Fay$$_(Fay$$add)(Fay$$_(Fay$$_(Fay$$add)(Fay$$_(Fay$$_(Prelude.rem)(Fay$$_(Fay$$_(Fay$$sub)(d))(1)))(c)))(c)))(1);if(Fay$$_(Fay$$_(Fay$$_(Fay$$and)(Fay$$_(Fay$$_(Fay$$lt)(d))(0)))(Fay$$_(Fay$$_(Fay$$gt)(c))(0))))return Fay$$_(Fay$$_(Fay$$sub)(Fay$$_(Fay$$_(Fay$$add)(Fay$$_(Fay$$_(Prelude.rem)(Fay$$_(Fay$$_(Fay$$add)(d))(1)))(c)))(c)))(1);
c=b;d=a;return Fay$$_(Fay$$_(Prelude.rem)(d))(c)})}};
Prelude.divMod=function(a){return function(b){return new Fay$$$(function(){var c=b,d=a;if(Fay$$_(Fay$$_(Fay$$_(Fay$$and)(Fay$$_(Fay$$_(Fay$$gt)(d))(0)))(Fay$$_(Fay$$_(Fay$$lt)(c))(0))))return function(a){if(Fay$$listLen(Fay$$_(a),2)){var b=Fay$$index(0,Fay$$_(a));a=Fay$$index(1,Fay$$_(a));return Fay$$list([Fay$$_(Fay$$_(Fay$$sub)(b))(1),Fay$$_(Fay$$_(Fay$$add)(Fay$$_(Fay$$_(Fay$$add)(a))(c)))(1)])}throw["unhandled case",a];}(Fay$$_(Fay$$_(Prelude.quotRem)(Fay$$_(Fay$$_(Fay$$sub)(d))(1)))(c));if(Fay$$_(Fay$$_(Fay$$_(Fay$$and)(Fay$$_(Fay$$_(Fay$$lt)(d))(0)))(Fay$$_(Fay$$_(Fay$$gt)(c))(1))))return function(a){if(Fay$$listLen(Fay$$_(a),
2)){var b=Fay$$index(0,Fay$$_(a));a=Fay$$index(1,Fay$$_(a));return Fay$$list([Fay$$_(Fay$$_(Fay$$sub)(b))(1),Fay$$_(Fay$$_(Fay$$sub)(Fay$$_(Fay$$_(Fay$$add)(a))(c)))(1)])}throw["unhandled case",a];}(Fay$$_(Fay$$_(Prelude.quotRem)(Fay$$_(Fay$$_(Fay$$add)(d))(1)))(c));c=b;d=a;return Fay$$_(Fay$$_(Prelude.quotRem)(d))(c)})}};
Prelude.min=function(a){return function(b){return new Fay$$$(function(){return Fay$$jsToFay(["unknown"],Math.min(Fay$$_(Fay$$fayToJs(["unknown"],a)),Fay$$_(Fay$$fayToJs(["unknown"],b))))})}};Prelude.max=function(a){return function(b){return new Fay$$$(function(){return Fay$$jsToFay(["unknown"],Math.max(Fay$$_(Fay$$fayToJs(["unknown"],a)),Fay$$_(Fay$$fayToJs(["unknown"],b))))})}};Prelude.recip=function(a){return new Fay$$$(function(){return Fay$$_(Fay$$_(Fay$$divi)(1))(a)})};Prelude.negate=function(a){return new Fay$$$(function(){return-Fay$$_(a)})};
Prelude.abs=function(a){return new Fay$$$(function(){return Fay$$_(Fay$$_(Fay$$_(Fay$$lt)(a))(0))?Fay$$_(Prelude.negate)(a):a})};Prelude.signum=function(a){return new Fay$$$(function(){return Fay$$_(Fay$$_(Fay$$_(Fay$$gt)(a))(0))?1:Fay$$_(Fay$$_(Fay$$_(Fay$$eq)(a))(0))?0:-1})};Prelude.pi=new Fay$$$(function(){return Fay$$jsToFay_double(Math.PI)});Prelude.exp=function(a){return new Fay$$$(function(){return Fay$$jsToFay_double(Math.exp(Fay$$fayToJs_double(a)))})};Prelude.sqrt=function(a){return new Fay$$$(function(){return Fay$$jsToFay_double(Math.sqrt(Fay$$fayToJs_double(a)))})};
Prelude.log=function(a){return new Fay$$$(function(){return Fay$$jsToFay_double(Math.log(Fay$$fayToJs_double(a)))})};Prelude.$42$$42$=new Fay$$$(function(){return Prelude.unsafePow});Prelude.$94$$94$=new Fay$$$(function(){return Prelude.unsafePow});Prelude.unsafePow=function(a){return function(b){return new Fay$$$(function(){return Fay$$jsToFay(["unknown"],Math.pow(Fay$$_(Fay$$fayToJs(["unknown"],a)),Fay$$_(Fay$$fayToJs(["unknown"],b))))})}};
Prelude.$94$=function(a){return function(b){return new Fay$$$(function(){var c=b,d=a;if(Fay$$_(Fay$$_(Fay$$_(Fay$$lt)(c))(0)))return Fay$$_(Prelude.error)(Fay$$list("(^): negative exponent"));if(Fay$$_(Fay$$_(Fay$$_(Fay$$eq)(c))(0)))return 1;if(Fay$$_(Fay$$_(Prelude.even)(c)))return function(){return new Fay$$$(function(){var a=new Fay$$$(function(){return Fay$$_(Fay$$_(Prelude.$94$)(d))(Fay$$_(Fay$$_(Prelude.quot)(c))(2))});return Fay$$_(Fay$$_(Fay$$mult)(a))(a)})}();c=b;d=a;return Fay$$_(Fay$$_(Fay$$mult)(d))(Fay$$_(Fay$$_(Prelude.$94$)(d))(Fay$$_(Fay$$_(Fay$$sub)(c))(1)))})}};
Prelude.logBase=function(a){return function(b){return new Fay$$$(function(){return Fay$$_(Fay$$_(Fay$$divi)(Fay$$_(Prelude.log)(b)))(Fay$$_(Prelude.log)(a))})}};Prelude.sin=function(a){return new Fay$$$(function(){return Fay$$jsToFay_double(Math.sin(Fay$$fayToJs_double(a)))})};Prelude.tan=function(a){return new Fay$$$(function(){return Fay$$jsToFay_double(Math.tan(Fay$$fayToJs_double(a)))})};Prelude.cos=function(a){return new Fay$$$(function(){return Fay$$jsToFay_double(Math.cos(Fay$$fayToJs_double(a)))})};
Prelude.asin=function(a){return new Fay$$$(function(){return Fay$$jsToFay_double(Math.asin(Fay$$fayToJs_double(a)))})};Prelude.atan=function(a){return new Fay$$$(function(){return Fay$$jsToFay_double(Math.atan(Fay$$fayToJs_double(a)))})};Prelude.acos=function(a){return new Fay$$$(function(){return Fay$$jsToFay_double(Math.acos(Fay$$fayToJs_double(a)))})};Prelude.sinh=function(a){return new Fay$$$(function(){return Fay$$_(Fay$$_(Fay$$divi)(Fay$$_(Fay$$_(Fay$$sub)(Fay$$_(Prelude.exp)(a)))(Fay$$_(Prelude.exp)(-Fay$$_(a)))))(2)})};
Prelude.tanh=function(a){return new Fay$$$(function(){return function(){return new Fay$$$(function(){var b=new Fay$$$(function(){return Fay$$_(Prelude.exp)(a)}),c=new Fay$$$(function(){return Fay$$_(Prelude.exp)(-Fay$$_(a))});return Fay$$_(Fay$$_(Fay$$divi)(Fay$$_(Fay$$_(Fay$$sub)(b))(c)))(Fay$$_(Fay$$_(Fay$$add)(b))(c))})}()})};Prelude.cosh=function(a){return new Fay$$$(function(){return Fay$$_(Fay$$_(Fay$$divi)(Fay$$_(Fay$$_(Fay$$add)(Fay$$_(Prelude.exp)(a)))(Fay$$_(Prelude.exp)(-Fay$$_(a)))))(2)})};
Prelude.asinh=function(a){return new Fay$$$(function(){return Fay$$_(Prelude.log)(Fay$$_(Fay$$_(Fay$$add)(a))(Fay$$_(Prelude.sqrt)(Fay$$_(Fay$$_(Fay$$add)(Fay$$_(Fay$$_(Prelude.$42$$42$)(a))(2)))(1))))})};Prelude.atanh=function(a){return new Fay$$$(function(){return Fay$$_(Fay$$_(Fay$$divi)(Fay$$_(Prelude.log)(Fay$$_(Fay$$_(Fay$$divi)(Fay$$_(Fay$$_(Fay$$add)(1))(a)))(Fay$$_(Fay$$_(Fay$$sub)(1))(a)))))(2)})};Prelude.acosh=function(a){return new Fay$$$(function(){return Fay$$_(Prelude.log)(Fay$$_(Fay$$_(Fay$$add)(a))(Fay$$_(Prelude.sqrt)(Fay$$_(Fay$$_(Fay$$sub)(Fay$$_(Fay$$_(Prelude.$42$$42$)(a))(2)))(1))))})};
Prelude.properFraction=function(a){return new Fay$$$(function(){return function(){return new Fay$$$(function(){var b=new Fay$$$(function(){return Fay$$_(Prelude.truncate)(a)});return Fay$$list([b,Fay$$_(Fay$$_(Fay$$sub)(a))(Fay$$_(Prelude.fromIntegral)(b))])})}()})};Prelude.truncate=function(a){return new Fay$$$(function(){return Fay$$_(Fay$$_(Fay$$_(Fay$$lt)(a))(0))?Fay$$_(Prelude.ceiling)(a):Fay$$_(Prelude.floor)(a)})};Prelude.round=function(a){return new Fay$$$(function(){return Fay$$jsToFay_int(Math.round(Fay$$fayToJs_double(a)))})};
Prelude.ceiling=function(a){return new Fay$$$(function(){return Fay$$jsToFay_int(Math.ceil(Fay$$fayToJs_double(a)))})};Prelude.floor=function(a){return new Fay$$$(function(){return Fay$$jsToFay_int(Math.floor(Fay$$fayToJs_double(a)))})};Prelude.subtract=new Fay$$$(function(){return Fay$$_(Prelude.flip)(Fay$$sub)});Prelude.even=function(a){return new Fay$$$(function(){return Fay$$_(Fay$$_(Fay$$eq)(Fay$$_(Fay$$_(Prelude.rem)(a))(2)))(0)})};Prelude.odd=function(a){return new Fay$$$(function(){return Fay$$_(Prelude.not)(Fay$$_(Prelude.even)(a))})};
Prelude.gcd=function(a){return function(b){return new Fay$$$(function(){return function(){var c=function(a){return function(b){return new Fay$$$(function(){if(0===Fay$$_(b)){var d=a;return d}d=a;return Fay$$_(Fay$$_(c)(b))(Fay$$_(Fay$$_(Prelude.rem)(d))(b))})}};return Fay$$_(Fay$$_(c)(Fay$$_(Prelude.abs)(a)))(Fay$$_(Prelude.abs)(b))}()})}};
Prelude.quot=function(a){return function(b){return new Fay$$$(function(){return Fay$$_(Fay$$_(Fay$$_(Fay$$eq)(b))(0))?Fay$$_(Prelude.error)(Fay$$list("Division by zero")):Fay$$_(Fay$$_(Prelude.quot$39$)(a))(b)})}};Prelude.quot$39$=function(a){return function(b){return new Fay$$$(function(){return Fay$$jsToFay_int(~~(Fay$$fayToJs_int(a)/Fay$$fayToJs_int(b)))})}};Prelude.quotRem=function(a){return function(b){return new Fay$$$(function(){return Fay$$list([Fay$$_(Fay$$_(Prelude.quot)(a))(b),Fay$$_(Fay$$_(Prelude.rem)(a))(b)])})}};
Prelude.rem=function(a){return function(b){return new Fay$$$(function(){return Fay$$_(Fay$$_(Fay$$_(Fay$$eq)(b))(0))?Fay$$_(Prelude.error)(Fay$$list("Division by zero")):Fay$$_(Fay$$_(Prelude.rem$39$)(a))(b)})}};Prelude.rem$39$=function(a){return function(b){return new Fay$$$(function(){return Fay$$jsToFay_int(Fay$$fayToJs_int(a)%Fay$$fayToJs_int(b))})}};Prelude.lcm=function(a){return function(b){return new Fay$$$(function(){return 0===Fay$$_(b)||0===Fay$$_(a)?0:Fay$$_(Prelude.abs)(Fay$$_(Fay$$_(Fay$$mult)(Fay$$_(Fay$$_(Prelude.quot)(a))(Fay$$_(Fay$$_(Prelude.gcd)(a))(b))))(b))})}};
Prelude.find=function(a){return function(b){return new Fay$$$(function(){var c=Fay$$_(b);if(c instanceof Fay$$Cons){var d=c.car;c=c.cdr;return Fay$$_(Fay$$_(a)(d))?Fay$$_(Prelude.Just)(d):Fay$$_(Fay$$_(Prelude.find)(a))(c)}if(null===Fay$$_(b))return Prelude.Nothing;throw["unhandled case in find",[a,b]];})}};
Prelude.filter=function(a){return function(b){return new Fay$$$(function(){var c=Fay$$_(b);if(c instanceof Fay$$Cons){var d=c.car;c=c.cdr;return Fay$$_(Fay$$_(a)(d))?Fay$$_(Fay$$_(Fay$$cons)(d))(Fay$$_(Fay$$_(Prelude.filter)(a))(c)):Fay$$_(Fay$$_(Prelude.filter)(a))(c)}if(null===Fay$$_(b))return null;throw["unhandled case in filter",[a,b]];})}};Prelude.$_null=function(a){return new Fay$$$(function(){return null===Fay$$_(a)?!0:!1})};
Prelude.map=function(a){return function(b){return new Fay$$$(function(){if(null===Fay$$_(b))return null;var c=Fay$$_(b);if(c instanceof Fay$$Cons){var d=c.car;c=c.cdr;return Fay$$_(Fay$$_(Fay$$cons)(Fay$$_(a)(d)))(Fay$$_(Fay$$_(Prelude.map)(a))(c))}throw["unhandled case in map",[a,b]];})}};Prelude.nub=function(a){return new Fay$$$(function(){return Fay$$_(Fay$$_(Prelude.nub$39$)(a))(null)})};
Prelude.nub$39$=function(a){return function(b){return new Fay$$$(function(){if(null===Fay$$_(a))return null;var c=Fay$$_(a);if(c instanceof Fay$$Cons){var d=c.car;c=c.cdr;return Fay$$_(Fay$$_(Fay$$_(Prelude.elem)(d))(b))?Fay$$_(Fay$$_(Prelude.nub$39$)(c))(b):Fay$$_(Fay$$_(Fay$$cons)(d))(Fay$$_(Fay$$_(Prelude.nub$39$)(c))(Fay$$_(Fay$$_(Fay$$cons)(d))(b)))}throw["unhandled case in nub'",[a,b]];})}};
Prelude.elem=function(a){return function(b){return new Fay$$$(function(){var c=Fay$$_(b);if(c instanceof Fay$$Cons){var d=c.car;c=c.cdr;return Fay$$_(Fay$$_(Fay$$or)(Fay$$_(Fay$$_(Fay$$eq)(a))(d)))(Fay$$_(Fay$$_(Prelude.elem)(a))(c))}if(null===Fay$$_(b))return!1;throw["unhandled case in elem",[a,b]];})}};Prelude.notElem=function(a){return function(b){return new Fay$$$(function(){return Fay$$_(Prelude.not)(Fay$$_(Fay$$_(Prelude.elem)(a))(b))})}};Prelude.sort=new Fay$$$(function(){return Fay$$_(Prelude.sortBy)(Prelude.compare)});
Prelude.sortBy=function(a){return new Fay$$$(function(){return Fay$$_(Fay$$_(Prelude.foldr)(Fay$$_(Prelude.insertBy)(a)))(null)})};
Prelude.insertBy=function(a){return function(b){return function(c){return new Fay$$$(function(){if(null===Fay$$_(c)){var d=b;return Fay$$list([d])}d=b;if(null===Fay$$_(c))d=Fay$$list([d]);else{var e=Fay$$_(c);if(e instanceof Fay$$Cons){var f=e.car;e=e.cdr;var h=Fay$$_(Fay$$_(a)(d))(f);d=Fay$$_(h)instanceof Prelude._GT?Fay$$_(Fay$$_(Fay$$cons)(f))(Fay$$_(Fay$$_(Fay$$_(Prelude.insertBy)(a))(d))(e)):Fay$$_(Fay$$_(Fay$$cons)(d))(c)}else throw["unhandled case",c];}return d})}}};
Prelude.conc=function(a){return function(b){return new Fay$$$(function(){var c=b,d=Fay$$_(a);if(d instanceof Fay$$Cons){var e=d.car;d=d.cdr;return Fay$$_(Fay$$_(Fay$$cons)(e))(Fay$$_(Fay$$_(Prelude.conc)(d))(c))}c=b;if(null===Fay$$_(a))return c;throw["unhandled case in conc",[a,b]];})}};Prelude.concat=new Fay$$$(function(){return Fay$$_(Fay$$_(Prelude.foldr)(Prelude.conc))(null)});Prelude.concatMap=function(a){return new Fay$$$(function(){return Fay$$_(Fay$$_(Prelude.foldr)(Fay$$_(Fay$$_(Prelude.$46$)(Prelude.$43$$43$))(a)))(null)})};
Prelude.foldr=function(a){return function(b){return function(c){return new Fay$$$(function(){if(null===Fay$$_(c)){var d=b;return d}d=Fay$$_(c);if(d instanceof Fay$$Cons){var e=d.car,f=d.cdr;d=b;return Fay$$_(Fay$$_(a)(e))(Fay$$_(Fay$$_(Fay$$_(Prelude.foldr)(a))(d))(f))}throw["unhandled case in foldr",[a,b,c]];})}}};
Prelude.foldr1=function(a){return function(b){return new Fay$$$(function(){if(Fay$$listLen(Fay$$_(b),1)){var c=Fay$$index(0,Fay$$_(b));return c}var d=Fay$$_(b);if(d instanceof Fay$$Cons)return c=d.car,d=d.cdr,Fay$$_(Fay$$_(a)(c))(Fay$$_(Fay$$_(Prelude.foldr1)(a))(d));if(null===Fay$$_(b))return Fay$$_(Prelude.error)(Fay$$list("foldr1: empty list"));throw["unhandled case in foldr1",[a,b]];})}};
Prelude.foldl=function(a){return function(b){return function(c){return new Fay$$$(function(){if(null===Fay$$_(c)){var d=b;return d}d=Fay$$_(c);if(d instanceof Fay$$Cons){var e=d.car,f=d.cdr;d=b;return Fay$$_(Fay$$_(Fay$$_(Prelude.foldl)(a))(Fay$$_(Fay$$_(a)(d))(e)))(f)}throw["unhandled case in foldl",[a,b,c]];})}}};
Prelude.foldl1=function(a){return function(b){return new Fay$$$(function(){var c=Fay$$_(b);if(c instanceof Fay$$Cons){var d=c.car;c=c.cdr;return Fay$$_(Fay$$_(Fay$$_(Prelude.foldl)(a))(d))(c)}if(null===Fay$$_(b))return Fay$$_(Prelude.error)(Fay$$list("foldl1: empty list"));throw["unhandled case in foldl1",[a,b]];})}};Prelude.$43$$43$=function(a){return function(b){return new Fay$$$(function(){return Fay$$_(Fay$$_(Prelude.conc)(a))(b)})}};
Prelude.$33$$33$=function(a){return function(b){return new Fay$$$(function(){return function(){var c=function(a){return function(b){return new Fay$$$(function(){if(null===Fay$$_(a))return Fay$$_(Prelude.error)(Fay$$list("(!!): index too large"));if(0===Fay$$_(b)){var d=Fay$$_(a);if(d instanceof Fay$$Cons)return d.car}d=Fay$$_(a);if(d instanceof Fay$$Cons)return d=d.cdr,Fay$$_(Fay$$_(c)(d))(Fay$$_(Fay$$_(Fay$$sub)(b))(1));throw["unhandled case in go",[a,b]];})}};return Fay$$_(Fay$$_(Fay$$_(Fay$$lt)(b))(0))?
Fay$$_(Prelude.error)(Fay$$list("(!!): negative index")):Fay$$_(Fay$$_(c)(a))(b)}()})}};Prelude.head=function(a){return new Fay$$$(function(){if(null===Fay$$_(a))return Fay$$_(Prelude.error)(Fay$$list("head: empty list"));var b=Fay$$_(a);if(b instanceof Fay$$Cons)return b.car;throw["unhandled case in head",[a]];})};
Prelude.tail=function(a){return new Fay$$$(function(){if(null===Fay$$_(a))return Fay$$_(Prelude.error)(Fay$$list("tail: empty list"));var b=Fay$$_(a);if(b instanceof Fay$$Cons)return b.cdr;throw["unhandled case in tail",[a]];})};
Prelude.init=function(a){return new Fay$$$(function(){if(null===Fay$$_(a))return Fay$$_(Prelude.error)(Fay$$list("init: empty list"));if(Fay$$listLen(Fay$$_(a),1))return null;var b=Fay$$_(a);if(b instanceof Fay$$Cons){var c=b.car;b=b.cdr;return Fay$$_(Fay$$_(Fay$$cons)(c))(Fay$$_(Prelude.init)(b))}throw["unhandled case in init",[a]];})};
Prelude.last=function(a){return new Fay$$$(function(){if(null===Fay$$_(a))return Fay$$_(Prelude.error)(Fay$$list("last: empty list"));if(Fay$$listLen(Fay$$_(a),1))return Fay$$index(0,Fay$$_(a));var b=Fay$$_(a);if(b instanceof Fay$$Cons)return b=b.cdr,Fay$$_(Prelude.last)(b);throw["unhandled case in last",[a]];})};Prelude.iterate=function(a){return function(b){return new Fay$$$(function(){return Fay$$_(Fay$$_(Fay$$cons)(b))(Fay$$_(Fay$$_(Prelude.iterate)(a))(Fay$$_(a)(b)))})}};Prelude.repeat=function(a){return new Fay$$$(function(){return Fay$$_(Fay$$_(Fay$$cons)(a))(Fay$$_(Prelude.repeat)(a))})};
Prelude.replicate=function(a){return function(b){return new Fay$$$(function(){return 0===Fay$$_(a)?null:Fay$$_(Fay$$_(Fay$$_(Fay$$lt)(a))(0))?null:Fay$$_(Fay$$_(Fay$$cons)(b))(Fay$$_(Fay$$_(Prelude.replicate)(Fay$$_(Fay$$_(Fay$$sub)(a))(1)))(b))})}};Prelude.cycle=function(a){return new Fay$$$(function(){return null===Fay$$_(a)?Fay$$_(Prelude.error)(Fay$$list("cycle: empty list")):function(){var b=new Fay$$$(function(){return Fay$$_(Fay$$_(Prelude.$43$$43$)(a))(b)});return b}()})};
Prelude.take=function(a){return function(b){return new Fay$$$(function(){if(0===Fay$$_(a)||null===Fay$$_(b))return null;var c=Fay$$_(b);if(c instanceof Fay$$Cons){var d=c.car;c=c.cdr;return Fay$$_(Fay$$_(Fay$$_(Fay$$lt)(a))(0))?null:Fay$$_(Fay$$_(Fay$$cons)(d))(Fay$$_(Fay$$_(Prelude.take)(Fay$$_(Fay$$_(Fay$$sub)(a))(1)))(c))}throw["unhandled case in take",[a,b]];})}};
Prelude.drop=function(a){return function(b){return new Fay$$$(function(){var c=b;if(0===Fay$$_(a))return c;if(null===Fay$$_(b))return null;c=Fay$$_(b);if(c instanceof Fay$$Cons)return c=c.cdr,Fay$$_(Fay$$_(Fay$$_(Fay$$lt)(a))(0))?b:Fay$$_(Fay$$_(Prelude.drop)(Fay$$_(Fay$$_(Fay$$sub)(a))(1)))(c);throw["unhandled case in drop",[a,b]];})}};
Prelude.splitAt=function(a){return function(b){return new Fay$$$(function(){var c=b;if(0===Fay$$_(a))return Fay$$list([null,c]);if(null===Fay$$_(b))return Fay$$list([null,null]);c=Fay$$_(b);if(c instanceof Fay$$Cons){var d=c.car;c=c.cdr;if(Fay$$_(Fay$$_(Fay$$_(Fay$$lt)(a))(0)))d=Fay$$list([null,Fay$$_(Fay$$_(Fay$$cons)(d))(c)]);else{var e=Fay$$_(Fay$$_(Prelude.splitAt)(Fay$$_(Fay$$_(Fay$$sub)(a))(1)))(c);if(Fay$$listLen(Fay$$_(e),2))c=Fay$$index(0,Fay$$_(e)),e=Fay$$index(1,Fay$$_(e)),d=Fay$$list([Fay$$_(Fay$$_(Fay$$cons)(d))(c),
e]);else throw["unhandled case",e];}return d}throw["unhandled case in splitAt",[a,b]];})}};Prelude.takeWhile=function(a){return function(b){return new Fay$$$(function(){if(null===Fay$$_(b))return null;var c=Fay$$_(b);if(c instanceof Fay$$Cons){var d=c.car;c=c.cdr;return Fay$$_(Fay$$_(a)(d))?Fay$$_(Fay$$_(Fay$$cons)(d))(Fay$$_(Fay$$_(Prelude.takeWhile)(a))(c)):null}throw["unhandled case in takeWhile",[a,b]];})}};
Prelude.dropWhile=function(a){return function(b){return new Fay$$$(function(){if(null===Fay$$_(b))return null;var c=Fay$$_(b);if(c instanceof Fay$$Cons){var d=c.car;c=c.cdr;return Fay$$_(Fay$$_(a)(d))?Fay$$_(Fay$$_(Prelude.dropWhile)(a))(c):Fay$$_(Fay$$_(Fay$$cons)(d))(c)}throw["unhandled case in dropWhile",[a,b]];})}};
Prelude.span=function(a){return function(b){return new Fay$$$(function(){if(null===Fay$$_(b))return Fay$$list([null,null]);var c=Fay$$_(b);if(c instanceof Fay$$Cons){var d=c.car;c=c.cdr;if(Fay$$_(Fay$$_(a)(d))){var e=Fay$$_(Fay$$_(Prelude.span)(a))(c);if(Fay$$listLen(Fay$$_(e),2))c=Fay$$index(0,Fay$$_(e)),e=Fay$$index(1,Fay$$_(e)),d=Fay$$list([Fay$$_(Fay$$_(Fay$$cons)(d))(c),e]);else throw["unhandled case",e];}else d=Fay$$list([null,Fay$$_(Fay$$_(Fay$$cons)(d))(c)]);return d}throw["unhandled case in span",
[a,b]];})}};Prelude.$_break=function(a){return new Fay$$$(function(){return Fay$$_(Prelude.span)(Fay$$_(Fay$$_(Prelude.$46$)(Prelude.not))(a))})};Prelude.zipWith=function(a){return function(b){return function(c){return new Fay$$$(function(){var d=Fay$$_(c);if(d instanceof Fay$$Cons){var e=d.car,f=d.cdr;d=Fay$$_(b);if(d instanceof Fay$$Cons){var h=d.car;d=d.cdr;return Fay$$_(Fay$$_(Fay$$cons)(Fay$$_(Fay$$_(a)(h))(e)))(Fay$$_(Fay$$_(Fay$$_(Prelude.zipWith)(a))(d))(f))}}return null})}}};
Prelude.zipWith3=function(a){return function(b){return function(c){return function(d){return new Fay$$$(function(){var e=Fay$$_(d);if(e instanceof Fay$$Cons){var f=e.car,h=e.cdr;e=Fay$$_(c);if(e instanceof Fay$$Cons){var g=e.car,k=e.cdr;e=Fay$$_(b);if(e instanceof Fay$$Cons){var l=e.car;e=e.cdr;return Fay$$_(Fay$$_(Fay$$cons)(Fay$$_(Fay$$_(Fay$$_(a)(l))(g))(f)))(Fay$$_(Fay$$_(Fay$$_(Fay$$_(Prelude.zipWith3)(a))(e))(k))(h))}}}return null})}}}};
Prelude.zip=function(a){return function(b){return new Fay$$$(function(){var c=Fay$$_(b);if(c instanceof Fay$$Cons){var d=c.car,e=c.cdr;c=Fay$$_(a);if(c instanceof Fay$$Cons){var f=c.car;c=c.cdr;return Fay$$_(Fay$$_(Fay$$cons)(Fay$$list([f,d])))(Fay$$_(Fay$$_(Prelude.zip)(c))(e))}}return null})}};
Prelude.zip3=function(a){return function(b){return function(c){return new Fay$$$(function(){var d=Fay$$_(c);if(d instanceof Fay$$Cons){var e=d.car,f=d.cdr;d=Fay$$_(b);if(d instanceof Fay$$Cons){var h=d.car,g=d.cdr;d=Fay$$_(a);if(d instanceof Fay$$Cons){var k=d.car;d=d.cdr;return Fay$$_(Fay$$_(Fay$$cons)(Fay$$list([k,h,e])))(Fay$$_(Fay$$_(Fay$$_(Prelude.zip3)(d))(g))(f))}}}return null})}}};
Prelude.unzip=function(a){return new Fay$$$(function(){var b=Fay$$_(a);if(b instanceof Fay$$Cons&&Fay$$listLen(Fay$$_(b.car),2)){var c=Fay$$index(0,Fay$$_(b.car)),d=Fay$$index(1,Fay$$_(b.car));b=b.cdr;var e=Fay$$_(Prelude.unzip)(b);if(Fay$$listLen(Fay$$_(e),2))b=Fay$$index(0,Fay$$_(e)),e=Fay$$index(1,Fay$$_(e)),c=Fay$$list([Fay$$_(Fay$$_(Fay$$cons)(c))(b),Fay$$_(Fay$$_(Fay$$cons)(d))(e)]);else throw["unhandled case",e];return c}if(null===Fay$$_(a))return Fay$$list([null,null]);throw["unhandled case in unzip",
[a]];})};
Prelude.unzip3=function(a){return new Fay$$$(function(){var b=Fay$$_(a);if(b instanceof Fay$$Cons&&Fay$$listLen(Fay$$_(b.car),3)){var c=Fay$$index(0,Fay$$_(b.car)),d=Fay$$index(1,Fay$$_(b.car)),e=Fay$$index(2,Fay$$_(b.car));b=b.cdr;var f=Fay$$_(Prelude.unzip3)(b);if(Fay$$listLen(Fay$$_(f),3)){b=Fay$$index(0,Fay$$_(f));var h=Fay$$index(1,Fay$$_(f));f=Fay$$index(2,Fay$$_(f));c=Fay$$list([Fay$$_(Fay$$_(Fay$$cons)(c))(b),Fay$$_(Fay$$_(Fay$$cons)(d))(h),Fay$$_(Fay$$_(Fay$$cons)(e))(f)])}else throw["unhandled case",f];
return c}if(null===Fay$$_(a))return Fay$$list([null,null,null]);throw["unhandled case in unzip3",[a]];})};
Prelude.lines=function(a){return new Fay$$$(function(){return null===Fay$$_(a)?null:function(){return function(a){if(Fay$$listLen(Fay$$_(a),2)){var b=Fay$$index(0,Fay$$_(a));if(null===Fay$$_(Fay$$index(1,Fay$$_(a))))return Fay$$list([b])}if(Fay$$listLen(Fay$$_(a),2)){b=Fay$$index(0,Fay$$_(a));var d=Fay$$_(Fay$$index(1,Fay$$_(a)));if(d instanceof Fay$$Cons)return a=d.cdr,Fay$$_(Fay$$_(Fay$$cons)(b))(Fay$$_(Prelude.lines)(a))}throw["unhandled case",a];}(Fay$$_(Fay$$_(Prelude.$_break)(function(a){return new Fay$$$(function(){return Fay$$_(Fay$$_(Fay$$or)(Fay$$_(Fay$$_(Fay$$eq)(a))("\r")))(Fay$$_(Fay$$_(Fay$$eq)(a))("\n"))})}))(a))}()})};
Prelude.unlines=function(a){return new Fay$$$(function(){if(null===Fay$$_(a))return null;var b=Fay$$_(a);if(b instanceof Fay$$Cons){var c=b.car;b=b.cdr;return Fay$$_(Fay$$_(Prelude.$43$$43$)(c))(Fay$$_(Fay$$_(Fay$$cons)("\n"))(Fay$$_(Prelude.unlines)(b)))}throw["unhandled case in unlines",[a]];})};
Prelude.words=function(a){return new Fay$$$(function(){return function(){var b=function(a){return new Fay$$$(function(){return Fay$$_(Fay$$_(Prelude.elem)(a))(Fay$$list(" \t\r\n\f\x0B"))})};return Fay$$_(function(a){return new Fay$$$(function(){if(null===Fay$$_(a))var c=null;else{var e=Fay$$_(Fay$$_(Prelude.$_break)(b))(a);if(Fay$$listLen(Fay$$_(e),2))c=Fay$$index(0,Fay$$_(e)),e=Fay$$index(1,Fay$$_(e)),c=Fay$$_(Fay$$_(Fay$$cons)(c))(Fay$$_(Prelude.words)(e));else throw["unhandled case",e];}return c})})(Fay$$_(Fay$$_(Prelude.dropWhile)(b))(a))}()})};
Prelude.unwords=new Fay$$$(function(){return Fay$$_(Prelude.intercalate)(Fay$$list(" "))});Prelude.and=function(a){return new Fay$$$(function(){if(null===Fay$$_(a))return!0;var b=Fay$$_(a);if(b instanceof Fay$$Cons){var c=b.car;b=b.cdr;return Fay$$_(Fay$$_(Fay$$and)(c))(Fay$$_(Prelude.and)(b))}throw["unhandled case in and",[a]];})};
Prelude.or=function(a){return new Fay$$$(function(){if(null===Fay$$_(a))return!1;var b=Fay$$_(a);if(b instanceof Fay$$Cons){var c=b.car;b=b.cdr;return Fay$$_(Fay$$_(Fay$$or)(c))(Fay$$_(Prelude.or)(b))}throw["unhandled case in or",[a]];})};
Prelude.any=function(a){return function(b){return new Fay$$$(function(){if(null===Fay$$_(b))return!1;var c=Fay$$_(b);if(c instanceof Fay$$Cons){var d=c.car;c=c.cdr;return Fay$$_(Fay$$_(Fay$$or)(Fay$$_(a)(d)))(Fay$$_(Fay$$_(Prelude.any)(a))(c))}throw["unhandled case in any",[a,b]];})}};
Prelude.all=function(a){return function(b){return new Fay$$$(function(){if(null===Fay$$_(b))return!0;var c=Fay$$_(b);if(c instanceof Fay$$Cons){var d=c.car;c=c.cdr;return Fay$$_(Fay$$_(Fay$$and)(Fay$$_(a)(d)))(Fay$$_(Fay$$_(Prelude.all)(a))(c))}throw["unhandled case in all",[a,b]];})}};
Prelude.intersperse=function(a){return function(b){return new Fay$$$(function(){if(null===Fay$$_(b))return null;var c=Fay$$_(b);if(c instanceof Fay$$Cons){var d=c.car;c=c.cdr;return Fay$$_(Fay$$_(Fay$$cons)(d))(Fay$$_(Fay$$_(Prelude.prependToAll)(a))(c))}throw["unhandled case in intersperse",[a,b]];})}};
Prelude.prependToAll=function(a){return function(b){return new Fay$$$(function(){if(null===Fay$$_(b))return null;var c=Fay$$_(b);if(c instanceof Fay$$Cons){var d=c.car;c=c.cdr;return Fay$$_(Fay$$_(Fay$$cons)(a))(Fay$$_(Fay$$_(Fay$$cons)(d))(Fay$$_(Fay$$_(Prelude.prependToAll)(a))(c)))}throw["unhandled case in prependToAll",[a,b]];})}};Prelude.intercalate=function(a){return function(b){return new Fay$$$(function(){return Fay$$_(Prelude.concat)(Fay$$_(Fay$$_(Prelude.intersperse)(a))(b))})}};
Prelude.maximum=function(a){return new Fay$$$(function(){return null===Fay$$_(a)?Fay$$_(Prelude.error)(Fay$$list("maximum: empty list")):Fay$$_(Fay$$_(Prelude.foldl1)(Prelude.max))(a)})};Prelude.minimum=function(a){return new Fay$$$(function(){return null===Fay$$_(a)?Fay$$_(Prelude.error)(Fay$$list("minimum: empty list")):Fay$$_(Fay$$_(Prelude.foldl1)(Prelude.min))(a)})};Prelude.product=function(a){return new Fay$$$(function(){return Fay$$_(Fay$$_(Fay$$_(Prelude.foldl)(Fay$$mult))(1))(a)})};
Prelude.sum=function(a){return new Fay$$$(function(){return Fay$$_(Fay$$_(Fay$$_(Prelude.foldl)(Fay$$add))(0))(a)})};Prelude.scanl=function(a){return function(b){return function(c){return new Fay$$$(function(){var d=Fay$$_(Fay$$_(Fay$$cons)(b));if(null===Fay$$_(c))var e=null;else{var f=Fay$$_(c);if(f instanceof Fay$$Cons)e=f.car,f=f.cdr,e=Fay$$_(Fay$$_(Fay$$_(Prelude.scanl)(a))(Fay$$_(Fay$$_(a)(b))(e)))(f);else throw["unhandled case",c];}return d(e)})}}};
Prelude.scanl1=function(a){return function(b){return new Fay$$$(function(){if(null===Fay$$_(b))return null;var c=Fay$$_(b);if(c instanceof Fay$$Cons){var d=c.car;c=c.cdr;return Fay$$_(Fay$$_(Fay$$_(Prelude.scanl)(a))(d))(c)}throw["unhandled case in scanl1",[a,b]];})}};
Prelude.scanr=function(a){return function(b){return function(c){return new Fay$$$(function(){if(null===Fay$$_(c)){var d=b;return Fay$$list([d])}d=Fay$$_(c);if(d instanceof Fay$$Cons){var e=d.car,f=d.cdr;d=b;d=Fay$$_(Fay$$_(Fay$$_(Prelude.scanr)(a))(d))(f);f=Fay$$_(d);f instanceof Fay$$Cons?(d=f.car,f=f.cdr,e=Fay$$_(Fay$$_(Fay$$cons)(Fay$$_(Fay$$_(a)(e))(d)))(Fay$$_(Fay$$_(Fay$$cons)(d))(f))):e=Prelude.$_undefined;return e}throw["unhandled case in scanr",[a,b,c]];})}}};
Prelude.scanr1=function(a){return function(b){return new Fay$$$(function(){if(null===Fay$$_(b))return null;if(Fay$$listLen(Fay$$_(b),1)){var c=Fay$$index(0,Fay$$_(b));return Fay$$list([c])}var d=Fay$$_(b);if(d instanceof Fay$$Cons){c=d.car;d=d.cdr;d=Fay$$_(Fay$$_(Prelude.scanr1)(a))(d);var e=Fay$$_(d);e instanceof Fay$$Cons?(d=e.car,e=e.cdr,c=Fay$$_(Fay$$_(Fay$$cons)(Fay$$_(Fay$$_(a)(c))(d)))(Fay$$_(Fay$$_(Fay$$cons)(d))(e))):c=Prelude.$_undefined;return c}throw["unhandled case in scanr1",[a,b]];
})}};Prelude.lookup=function(a){return function(b){return new Fay$$$(function(){if(null===Fay$$_(b))return Prelude.Nothing;var c=Fay$$_(b);if(c instanceof Fay$$Cons&&Fay$$listLen(Fay$$_(c.car),2)){var d=Fay$$index(0,Fay$$_(c.car)),e=Fay$$index(1,Fay$$_(c.car));c=c.cdr;return Fay$$_(Fay$$_(Fay$$_(Fay$$eq)(a))(d))?Fay$$_(Prelude.Just)(e):Fay$$_(Fay$$_(Prelude.lookup)(a))(c)}throw["unhandled case in lookup",[a,b]];})}};Prelude.length=function(a){return new Fay$$$(function(){return Fay$$_(Fay$$_(Prelude.length$39$)(0))(a)})};
Prelude.length$39$=function(a){return function(b){return new Fay$$$(function(){var c=Fay$$_(b);if(c instanceof Fay$$Cons){c=c.cdr;var d=a;return Fay$$_(Fay$$_(Prelude.length$39$)(Fay$$_(Fay$$_(Fay$$add)(d))(1)))(c)}return d=a})}};
Prelude.reverse=function(a){return new Fay$$$(function(){var b=Fay$$_(a);if(b instanceof Fay$$Cons){var c=b.car;b=b.cdr;return Fay$$_(Fay$$_(Prelude.$43$$43$)(Fay$$_(Prelude.reverse)(b)))(Fay$$list([c]))}if(null===Fay$$_(a))return null;throw["unhandled case in reverse",[a]];})};Prelude.print=function(a){return new Fay$$$(function(){var b=Fay$$jsToFay,c=Fay$$fayToJs(["automatic"],a);console&&console.log&&console.log(c);return new Fay$$Monad(b(["unknown"],void 0))})};
Prelude.putStrLn=function(a){return new Fay$$$(function(){var b=Fay$$jsToFay,c=Fay$$fayToJs_string(a);console&&console.log&&console.log(c);return new Fay$$Monad(b(["unknown"],void 0))})};Prelude.ifThenElse=function(a){return function(b){return function(c){return new Fay$$$(function(){return Fay$$_(a)?b:c})}}};
Fay$$objConcat(Fay$$fayToJsHash,{Just:function(a,b,c){var d={instance:"Just"};a=Fay$$fayToJs(b&&b[0]?b[0]:"automatic"===a[0]?["automatic"]:["unknown"],c.slot1);void 0!==a&&(d.slot1=a);return d},Nothing:function(a,b,c){return{instance:"Nothing"}},Left:function(a,b,c){var d={instance:"Left"};a=Fay$$fayToJs(b&&b[0]?b[0]:"automatic"===a[0]?["automatic"]:["unknown"],c.slot1);void 0!==a&&(d.slot1=a);return d},Right:function(a,b,c){var d={instance:"Right"};a=Fay$$fayToJs(b&&b[1]?b[1]:"automatic"===a[0]?
["automatic"]:["unknown"],c.slot1);void 0!==a&&(d.slot1=a);return d},GT:function(a,b,c){return{instance:"GT"}},LT:function(a,b,c){return{instance:"LT"}},EQ:function(a,b,c){return{instance:"EQ"}}});
Fay$$objConcat(Fay$$jsToFayHash,{Just:function(a,b,c){return new Prelude._Just(Fay$$jsToFay(b&&b[0]?b[0]:"automatic"===a[0]?["automatic"]:["unknown"],c.slot1))},Nothing:function(a,b,c){return new Prelude._Nothing},Left:function(a,b,c){return new Prelude._Left(Fay$$jsToFay(b&&b[0]?b[0]:"automatic"===a[0]?["automatic"]:["unknown"],c.slot1))},Right:function(a,b,c){return new Prelude._Right(Fay$$jsToFay(b&&b[1]?b[1]:"automatic"===a[0]?["automatic"]:["unknown"],c.slot1))},GT:function(a,b,c){return new Prelude._GT},
LT:function(a,b,c){return new Prelude._LT},EQ:function(a,b,c){return new Prelude._EQ}});var FFI={};
